### ISSUE TITLE
Support for non qwerty keyboard layout

### ISSUE THREAD

**Issue by danielboone** [asweigart/pyautogui#10]
Hello,
I discovered pyautogui today as a great replacement for SendKeys and pywinauto. Unfortunately for me I noticed typewrite and other keyboard functions returns wrong characters on win7 with a different keyboard (dvorak) layout. I tried a temporary swap with win32api.LoadKeyboardLayout('00000409',1) but it did not solve the problem.
Best regards,

**Comment by mvbentes** [comment]
I had been using it with a custom layout made with windows keyboard layout creator and had no trouble with the letters, which are positioned kind of like in dvorak, as long as the receiving window was using the same layout as the python script.

I had trouble, however, with the / character. Are the troublesome characters such that you could type them with alt or ctrl combinations? Then you might have the same trouble as I had. I proposed a pull for that.

**Comment by asweigart** [comment]
Folding this into issue #137

**Comment by JulienRouse** [comment]
For anybody having trouble as well with non qwerty/qwertz keyboard: 

if you need to use the msgbox function (alert, confirm, password, prompt), you can use this:

    import pyperclip
    import import pyautogui
    
    def my_write(msg):
        pyperclip.copy(msg) # copy msg in the clipboard
        pyautogui.hotkey('ctrl', 'v') # paste msg
