### ISSUE TITLE
Installation Problem - Python 3.4 - Raspberry Pi

### ISSUE THREAD

**Issue by CelestiorTheGreat** [asweigart/pyautogui#104]
I have faced a serious problem trying to install pyautogui on my Raspberry Pi using Python 3.4.
It worked well on my main machine using Python 3.5 however.

The problem is that every time I try to install it by using:
`pip3 install pyautogui` , I get the error `Import Error: No Module named "new"` .

The strange thing about this is, that the "new" module has been renamed to "types" in python 3, thereby causing the error. I tried cloning the newest version directly from this github page resulting in the same error... Does Anyone have a fix for this?

**Comment by glitchassassin** [comment]
Can you post the full output of pip3? It doesn't seem `pyautogui` itself uses the "new" module, so I'm wondering if it's maybe triggering because of a dependency that is being installed along side.

**Comment by asweigart** [comment]
I think this might be a problem in the user's code rather than PyAutoGUI. This error would be raised if the code was `import new`, which does not appear in PyAutoGUI's code. I'm closing this.
