### ISSUE TITLE
installation problem on windows

### ISSUE THREAD

**Issue by mykel347** [asweigart/pyautogui#106]
When I ran pip install pyautogui on windows I get this error

 ` Using cached PyMsgBox-1.0.3.zip
Collecting PyTweening>=1.0.1 (from pyautogui)
  Using cached PyTweening-1.0.3.zip
Collecting Pillow (from pyautogui)
  Using cached Pillow-3.4.2-cp35-cp35m-win32.whl
Collecting pyscreeze (from pyautogui)
  Using cached PyScreeze-0.1.8.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users.....\AppData\Local\Temp\pip-build-li581zwg\pyscreeze\setup.py", line 6,
 in <module>
        version=**import**('pyscreeze').**version**,
      File "c:\users....\appdata\local\temp\pip-build-li581zwg\pyscreeze\pyscreeze__init__
.py", line 21, in <module>
        from PIL import Image
    ImportError: No module named 'PIL'

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in C:\Users....\AppData\Local\T
emp\pip-build-li581zwg\pyscreeze`

**Comment by glitchassassin** [comment]
This is actually a [known issue with PyScreeze](https://github.com/asweigart/pyscreeze/issues/20).

What's your version of pip?

**Comment by mykel347** [comment]
pip 8.1.2

**Comment by asweigart** [comment]
Fixed in https://github.com/asweigart/pyscreeze/pull/17
