### ISSUE TITLE
Really weird keystroke problem with Shell32 and pyautogui. Keystrokes not sending

### ISSUE THREAD

**Issue by Haroldyolo** [asweigart/pyautogui#107]
Hi there,
I am having a frustrating and weird problem with sending keystrokes. Few things to clarify first. The application doesn't have any anti-cheat and the sending keystrokes works under windows XP on virtual machine, but not on my main machine under windows 10.
Using simple code as
```
pyautogui.typewrite("4") or
pyautogui.KeyDown("4") or
pyautogui.press("4") or
Shell.sendkey("4")
```
simply won't send the key to the application I am trying on, but it will send it everywhere else:browser,notepad you name it.
Please help as I am stuck.....

**Comment by Haroldyolo** [comment]
A bit more info after testing.... tried another two completely different machines with Windows 7 on both and it works on one, but not on the other.

**Comment by glitchassassin** [comment]
Any anti-virus software on any of the computers?

**Comment by Haroldyolo** [comment]
I got avast on the win10 but tried turning that off and on and still same
issue.

**Comment by asweigart** [comment]
Sorry for the delay in responding to this. Without more concrete repro steps, I'm afraid I can't do anything with this.
