### ISSUE TITLE
pyautogui.size() gives wrong resolution on Windows 10 laptop

### ISSUE THREAD

**Issue by anubhav-s** [asweigart/pyautogui#110]
**Description:**

pyautogui.size(), pyautogui.position(), pyautogui.moveTo() and some more functions are giving wrong output on Windows 10 and Windows 8 laptops (I tried on Lenovo and Dell). However, things are working fine on desktops with Windows 8 and Windows 10 versions. 

Python version: 2.7.12 and 2.7.11

Please see the attached image.

![windows10_pyautogui_wrong_resolution](https://cloud.githubusercontent.com/assets/3470558/20616879/713800dc-b30b-11e6-930a-3506dc5c2ce6.jpg)

**Comment by studioj** [comment]
I also saw this

**Comment by glitchassassin** [comment]
What are the models of the laptops?

**Comment by glitchassassin** [comment]
Some preliminary research suggests that it might be the screen DPI setting.

In Windows 8, you can right-click on the desktop, select Screen Resolution, and then click "Make text and other items larger or smaller". This might be different for Windows 10, but I believe it still exists.

**Comment by studioj** [comment]
yes indeed that's it.
Put the slider to 100% to get the proper size...
![image](https://cloud.githubusercontent.com/assets/22102283/20634606/f4bea4e6-b352-11e6-9c52-7818d07d563b.png)

**Comment by dragon788** [comment]
#116 has a clever workaround for this it seems.

**Comment by asweigart** [comment]
I've added the DPI scaling fix to 0.9.35, so hopefully this is now fixed.
