### ISSUE TITLE
Pyautogui Documentation: 'space' hotkey not present in the list of keys given in the documentation

### ISSUE THREAD

**Issue by achitroj** [asweigart/pyautogui#112]
In the documentation given here- [http://pyautogui.readthedocs.io/en/latest/keyboard.html#keyboard-keys](url) , '**space**' key is not mentioned.

**Comment by KyleWJohnston** [comment]
The fourth option listed (right after `'\r'`) is a space (`' '`). It doesn't explicitly say the word space, but I'm assuming it has the same functionality.

**Comment by glitchassassin** [comment]
The keyword `space` was added for issue #85, and there's a proposed fix for the documentation in pull request #105.

**Comment by achitroj** [comment]
Yes that's right! And there is already an issue on this, as mentioned by @glitchassassin .

**Comment by asweigart** [comment]
Closed. Fixed in pull request #105
