### ISSUE TITLE
Windows Installation Problem

### ISSUE THREAD

**Issue by frakman1** [asweigart/pyautogui#114]
Windows 7. Python 2.7 32 bit. 

Although I was able to install it, I was not able to get the alertbox or locateOnScreen functions to work. (The mouse 'position' function, however, works as expected)

```
PS C:\Python27\lifx-simple> pip install pyautogui
Requirement already satisfied: pyautogui in c:\python27\lib\site-packages\pyautogui-0.9.5-py2.7.egg
PS C:\Python27\lifx-simple> python
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyautogui
>>> pyautogui.alert('This is an alert box.')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'alert'
>>> button7location = pyautogui.locateOnScreen('button.png')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'locateOnScreen'
PS C:\Python27\lifx-simple> pip --version
pip 9.0.1 from C:\Python27\Lib\site-packages (python 2.7)
```

**Comment by wangtubs** [comment]
I also met the same problem. why no people answer this question?

**Comment by glitchassassin** [comment]
What happens when you run `pip install pyscreeze` and `pip install pymsgbox`?

**Comment by frakman1** [comment]
Thank you for the suggestions. I don't remember what I did to fix it but I think it had to do with installing `pillow`.

**Comment by frakman1** [comment]
Pillow had to be manually installed from [binary](https://pypi.python.org/pypi/Pillow/2.2.1#downloads) before those dependencies correctly installed. Then everything worked correctly.
