### ISSUE TITLE
OSError: [WinError 6] The handle is invalid, after update to Python 3.6

### ISSUE THREAD

**Issue by ningyuansg** [asweigart/pyautogui#117]
[The script I wrote](https://github.com/ningyuansg/bumblebee) worked fine on Python 3.4, on update to Python 3.6 (and installing all modules used in the script), I get a 'Python has stopped working'.

In order to pinpoint which module was not working properly, I opened the interactive Python shell and tried some basic methods in the external modules I used in the script. Of those, only pyautogui raised an error.

```
>>> import pyautogui
>>> pyautogui.click()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\me\AppData\Local\Programs\Python\Python36\lib\site-packages\pyautogui\__init__.py", line 362, in click
    platformModule._click(x, y, 'left')
  File "C:\Users\me\AppData\Local\Programs\Python\Python36\lib\site-packages\pyautogui\_pyautogui_win.py", line 437, in _click
    _sendMouseEvent(MOUSEEVENTF_LEFTCLICK, x, y)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36\lib\site-packages\pyautogui\_pyautogui_win.py", line 480, in _sendMouseEvent
    raise ctypes.WinError()
OSError: [WinError 6] The handle is invalid.
```

I have since uninstalled Python 3.4, but the script has previously worked as expected with that installation on the same machine. I'm running Windows 10 with Python 3.6 (64-bit).

**Comment by ahlidap** [comment]
Hi,

I'm facing this issue too.
I developed a small script in Linux, when when moved to windows I got this same error.

Any news on this?
(I haven't tried with a previous python version yet)

**Comment by ningyuansg** [comment]
@ahlidap Sorry, I haven't had any headway with this issue, and I've since abandoned that particular project.

**Comment by glitchassassin** [comment]
Confirmed that this is an issue in both the 64-bit and 32-bit versions of Python 3.6. I was able to trigger this error reliably after two calls to `click()` - the first didn't throw the error.

Does this match up with what you're seeing?

**Comment by asweigart** [comment]
This has been fixed with https://github.com/asweigart/pyautogui/pull/94 Thanks!
