### ISSUE TITLE
Possible to dismiss alert, confirmation box automatically after a while?

### ISSUE THREAD

**Issue by herbzhao** [asweigart/pyautogui#118]
Dear all,
I just started using pyautogui and I want to alert users before my script taking action so they can get away from the keyboard. Anyway to implement this? 
It seems like whenever the popup happens, the script also stops.

**Comment by glitchassassin** [comment]
Ordinarily, that's how it's supposed to work. Popups block program execution until some user input is received.

You can [create a popup with a timeout](http://stackoverflow.com/questions/1917198/how-to-launch-a-python-tkinter-dialog-box-that-self-destructs), though, using Tkinter (which usually comes pre-installed with Python).

**Comment by asweigart** [comment]
This seems like something I'd like to put in, with the default behavior being not timing out. Does anyone else have opinions on if adding this feature would be a bad idea?

**Comment by glitchassassin** [comment]
If pyautogui already imports Tkinter, you shouldn't have any new issues. (On my phone atm, can't check)

If it doesn't, I've found Tkinter can dramatically slow down launch of onefile exes built with pyinstaller, so depending on how users deploy pyautogui scripts, that might be an issue worth considering.

**Comment by asweigart** [comment]
I've added a new `timeout` parameter to the four message box functions in https://github.com/asweigart/PyMsgBox/commit/4cd64255364ce23b3b672af0ab8b1d5dcbac19f2 so this feature now exists in PyAutoGUI as well:

```
>>> import pymsgbox
>>> pymsgbox.alert(timeout=2000)  # times out after 2 seconds
'Timeout'

```

**Comment by metaperl** [comment]
Please update [the docs](https://pyautogui.readthedocs.io/en/latest/msgbox.html) to reflect the `timeout` feature. I forked the repo and was going to add docs for this, but saw that there are 40 pull requests open and dont want to do something and not have it integrated.
