### ISSUE TITLE
pyautogui.size() on OS X Retina Macbook Pro 

### ISSUE THREAD

**Issue by dsiah** [asweigart/pyautogui#12]
Hello,

I was going through basic usage of pyautogui and I found that the command 
``` python
 pyautogui.size()
``` 
causes my python interpreter to freeze. I tried using it in a file and that also hung. Is this a problem with Retina, OS X, laptops, etc?

Note: the other commands seem to be working properly -- only size is giving me trouble

Thanks

**Comment by jeremygray** [comment]
Related, not sure if you'd like a separate issue for this: On Mac 10.9.5 with a retina display 1440 x 900, I get `screenshot()` sizes that are exactly twice as large as expected. This appears to carry through to the `locate()` family of functions, and return coordinates that are off by a factor of 2.

    >>>> pyautogui.screenshot()
    <PIL.PngImagePlugin.PngImageFile image mode=RGB size=2880x1800 at 0x106CFCF80>

**Comment by faurehu** [comment]
I ran a tracer to follow the interpretation of pyautogui and apparently it gets stuck here:
`pyautogui/__init__.py:122   line          return platformModule._size()`

**Comment by aaruff** [comment]
I also experienced the same issue (MacBook Pro 10.10.3 (Retina, 13-inch, Late 2013)). Though I remedied the issue by replace 0 with Quartz.CGMainDisplayID() in the _size function. Further investigation is required to determine why exactly this issue arose in the first place.

```python
def _size():
    return Quartz.CGDisplayPixelsWide(Quartz.CGMainDisplayID()), Quartz.CGDisplayPixelsHigh(Quartz.CGMainDisplayID())
```

**Comment by kasperschnack** [comment]
Pyautogui uses screencaps to find the location of stuff on the screen. The problem on macs with a retina display is that the screen output have double the number of pixels, to take advantage of the system’s greater pixel density for a crisper image.Therefore, when you take a screenshot, you get an image containing double the number of pixels than the same image from a non-retina Mac. I'm currently looking into whether it is possible to resize the image and still be able to find a match (one pixel off and theres no match if not using cv2's fuzzy search)
[source](http://www.macissues.com/2014/03/29/adjust-retina-macbook-screenshots-to-be-actual-size/)
