### ISSUE TITLE
can't screenshot from pyautogui

### ISSUE THREAD

**Issue by wangtubs** [asweigart/pyautogui#120]
```
    pyautogui.screenshot('foo.png')
AttributeError: 'module' object has no attribute 'screenshot'
```
while the dir(pyautogui) output:
`['FAILSAFE', 'FailSafeException', 'KEYBOARD_KEYS', 'KEY_NAMES', 'MINIMUM_DURATION', 'MINIMUM_SLEEP', 'PAUSE', 'Window', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', '__version__', '_autoPause', '_failSafeCheck', '_mouseMoveDrag', '_pyautogui_win', '_unpackXY', '_window_win', 'absolute_import', 'click', 'collections', 'displayMousePosition', 'division', 'doubleClick', 'dragRel', 'dragTo', 'getPointOnLine', 'getWindow', 'getWindows', 'hotkey', 'hscroll', 'isShiftCharacter', 'isValidKey', 'keyDown', 'keyUp', 'linear', 'middleClick', 'mouseDown', 'mouseUp', 'moveRel', 'moveTo', 'onScreen', 'platformModule', 'position', 'press', 'print_function', 'rightClick', 'scroll', 'size', 'sys', 'time', 'tripleClick', 'typewrite', 'vscroll']`
seems the pyautogui lack some of attibutes.
I installed pyautogui from git clone https://github.com/asweigart/pyautogui
I also find the pip install pyautogui does not work on windows
my computer is windows 10 64x, python version is python 2.7

**Comment by glitchassassin** [comment]
What happens when you run `pip install pyscreeze` and `pip install pymsgbox`?

These methods are supposed to be imported from those modules, but they fail silently if there's an exception (like if the modules aren't installed.

**Comment by wangtubs** [comment]
ok. I reinstalled python 2.7.13. now is fine. but the pyautogui.locateCenterOnScreen() works very bad.
```
>>> x,y=pyautogui.locateCenterOnScreen('1.png')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'NoneType' object is not iterable
```
sometimes it is working, but many times it gives error. it is not reliable and stable.

**Comment by glitchassassin** [comment]
Install `cv2` to let pyautogui use OpenCV's template matching routines. That should be more reliable. Otherwise, it'll only detect an exact pixel match.

**Comment by acust** [comment]
If `pip install cv2` doesn't work, try `pip install opencv-python`

**Comment by glitchassassin** [comment]
Are you on Linux or Windows?

**Comment by asweigart** [comment]
This has been fixed. Thanks for pointing out this issue.
