### ISSUE TITLE
recorder functionality planned???

### ISSUE THREAD

**Issue by nnako** [asweigart/pyautogui#121]
Hi,

I love this module!!! Sometimes, moving to the desired mouse coordinates, writing them down, translating it to code... and building a reasonable sequence takes very long. I could imagine a simple "recorder" function which produces the Python command sequence while operating on the screen in a "normal" way. Like macros can be created in Excel. These sequences can later be adjusted and refined.

Would this be a feature for a future version of `pyautogui`?

**Comment by asweigart** [comment]
Yes, this is on the roadmap and is managed by issue #127, so please post any ideas or comments there. Thanks!
