### ISSUE TITLE
Question: How to use Window module on win32?

### ISSUE THREAD

**Issue by antonbabkin** [asweigart/pyautogui#123]
I am trying to use window manipulation functions from _windows_win module, and for some reason they are not available.

I try this:

    import pyautogui
    pyautogui.Window

And get error: `AttributeError: module 'pyautogui' has no attribute 'Window'`.
Same with `getWindow` and `getWindows`.

What am I doing wrong? If I understand it correctly, [these lines](https://github.com/asweigart/pyautogui/blob/master/pyautogui/__init__.py#L111) from __init.py__ should initialize the module:

    elif sys.platform == 'win32':
    from . import _pyautogui_win as platformModule
    from ._window_win import Window, getWindows, getWindow

And I am running this on Windows 10, `pypiwin32` installed.

**Comment by asweigart** [comment]
Currently these aren't working, and this file will be removed from pyautogui soon. This functionality will be added to PyGetWindow, which is unfinished but under development here: https://github.com/asweigart/pygetwindow

When it is done, it'll be included with PyAutoGUI, but I'm not sure when that will be. Sorry!
