### ISSUE TITLE
Making pyAutoGUI work on a remote machine....

### ISSUE THREAD

**Issue by LittleFrog1959** [asweigart/pyautogui#124]
Hi,
I have found that it's possible to make some aspects of pyAutoGUI work on a remote machine (e.g. moveTo and click) and my question is whether this could be made to work for other functions (e.g. alert).

If my Python is running on 192.168.1.1 and I want to control the mouse and keyboard on 192.168.1.2, this works;
```
import pyautogui
import Xlib
from time import sleep

class g:
    xDisplay = "192.168.1.2:0.0"

# This is the magic bit
pyautogui.platformModule._display = Xlib.display.Display (g.xDisplay)

# Lets print out the size of the remote screen
screenWidth, screenHeight = pyautogui.size()
print screenWidth, screenHeight

# Put a message box on the screen
# pyautogui.alert ("Hi David")      # Goes to local display

# Take a screen shot
#pyautogui.screenshot ("dgw.png")   # Gets local display

# Go into a location on the remote screen
pyautogui.moveTo (770, 200)
sleep (1)
pyautogui.click ()
sleep (1)

```
I have to enter something like this first on .2
Old Debian machine
```
    export DISPLAY=":0.0"
    xhost +
```
I have managed to make it work on a newer Ubuntu machine by adding this to lighdm config;
Create a text file here;
` /usr/share/lightdm/lightdm.conf.d/100-remoteX.conf
`
Then enter the following;
```
[SeatDefaults]
xserver-allow-tcp=true
```
Getting back to the question, I wonder if there's any way to make more of the functions work on the remote machine?

Thanks for your attention.

Dave

**Comment by asweigart** [comment]
Can you just pass the "192.168.1.2:0.0" string to Xlib.display.Display()? Unfortunately, the pymsgbox code has to run on the system running the python script (it uses Python's tkinter module to work) so the message boxes can't appear on the remote system.

Remote access is tricky: PyAutoGUI is meant to run on Win/Mac/Linux, and I'm not sure how easy it would be to provide a uniform interface for all three. Though I'm interested in accepting PRs if you can get this working.

**Comment by lssfreesky** [comment]
this does not work in python 3, is there any way to get rid of the problem "ModuleNotFoundError: No module named 'fcntl'?
