### ISSUE TITLE
Emulating a swipe on Touchscreen

### ISSUE THREAD

**Issue by risjain** [asweigart/pyautogui#125]
Hi:

I'm trying to emulate a swiping action using

moveTo(locate_on_Screen)
mouseDown()
mouseUp(x = new_x, y = new_y, duration = 0.1)

But, the swipe isn't detected. Is this expected?

**Comment by glitchassassin** [comment]
Swipes are generally treated differently by the OS than "click-and-drag" events. I think you'd need to leverage an entirely different API on the OS level.

**Comment by risjain** [comment]
Thanks!

**Comment by asweigart** [comment]
Yes. For now, PyAutoGUI really only supports Windows/Mac/Linux, and not Android or iOS.

If you just want to drag, you can use dragTo() and dragRel() (which operate the same as moveTo() and moveRel() but while holding down a mouse button (left button by default))
