### ISSUE TITLE
io error exception when trying to write dev.null in google app engine 

### ISSUE THREAD

**Issue by anush0247** [asweigart/pyautogui#138]
Hey, we are deploying the code in google app engine, where we will be having the read-only file system.

below source code and line:

https://github.com/asweigart/pyscreeze/blob/master/pyscreeze/__init__.py#L50 

trying to write to file system, we need handle the IO Exception here

**Comment by glitchassassin** [comment]
What's the underlying OS? `pyautogui` uses `scrot` output to temporary files to capture the screen in Linux, so I'm not sure it can work with a read-only file system.

**Comment by asweigart** [comment]
Fixed in https://github.com/asweigart/pyscreeze/commit/ca1f0e68600f7caceb3d91f4eb9d22e8dd638de4 by taking out the devnull stuff, which is only in there for a hyptothetical deadlock fix. We can revisit that issue if it actually comes up for someone. I'm not too concerned about it.

**Comment by asweigart** [comment]
Thanks everyon!
