### ISSUE TITLE
Can't type letters with typewrite()

### ISSUE THREAD

**Issue by asweigart** [asweigart/pyautogui#142]
Investigate the issue this user is having: https://stackoverflow.com/questions/35582155/missing-symbols-in-pyautogui-typewriter

**Comment by asweigart** [comment]
Also this issue: https://stackoverflow.com/questions/33844149/pyautogui-typewrite-is-writing-only-numbers

**Comment by TheRealNoob** [comment]
I am using PyAutoGui 0.9.36 on Win7x64.  I am using it in a script which is meant to run 24/7.  Every couple of minutes I called the typewrite() function to say "/Challenge 6" and "/Accept".  However I noticed that after about 8 hours it made the mistake of writing just "'Challenge 6" and at 16 hours it wrote the same 5 times in a row.

**Comment by asweigart** [comment]
This seems to be related with issue 70 (which I believe is a non-qwerty keyboard issue). I'm closing this since issue 70 is open.
