### ISSUE TITLE
pyautogui.hotkey('ctrl','c') - KeyboardInterrupt

### ISSUE THREAD

**Issue by Ceuten** [asweigart/pyautogui#148]
Using pyautogui.hotkey('ctrl','c') to copy marked text trickers 'KeyboardInterupt'.

Which I guess is expected behavior, but not the intended copy marked text behavior?

Instead, at least for windows, pyautogui.hotkey('ctrl','insert') can be used to copy marked text.

**Comment by asweigart** [comment]
Sorry for the delay in replying.

I can't repro this on my machine. I suspect you have the interactive shell window focused when the function call happens, and that's causing the KeyboardInterrupt.
