### ISSUE TITLE
Fixable Hotkey Bug and Small Documentation Issues

### ISSUE THREAD

**Issue by lydianchord** [asweigart/pyautogui#15]
Hi, I thought I'd let you know that the <code>hotkey()</code> function doesn't always work on Windows 7. I managed to fix this issue in a similar keyboard automation script I was working on myself by adding the extended-key flag into the <code>ctypes.windll.user32.keybd_event()</code> function. For example, the following executes SHIFT + DOWN properly, which doesn't happen when you use `hotkey('shift', 'down')` in pyautogui:

``` python
ctypes.windll.user32.keybd_event(0x10, 0, 0, 0)    # SHIFT
ctypes.windll.user32.keybd_event(0x28, 0, 1, 0)    # DOWN, third argument is KEYEVENTF_EXTENDEDKEY
ctypes.windll.user32.keybd_event(0x28, 0, (1 | 2), 0)    # DOWN
ctypes.windll.user32.keybd_event(0x10, 0, 2, 0)    # SHIFT
```

I'm not completely sure why this needs the extended-key flag to work even though extended keys don't need the flag when used in isolation, but it makes certain useful hotkeys work properly. Additionally, adding the extended-key flag to key presses that don't need it doesn't seem to cause any issues, so the following also works:

``` python
ctypes.windll.user32.keybd_event(0x10, 0, 1, 0)    # SHIFT
ctypes.windll.user32.keybd_event(0x28, 0, 1, 0)    # DOWN
ctypes.windll.user32.keybd_event(0x28, 0, (1 | 2), 0)    # DOWN
ctypes.windll.user32.keybd_event(0x10, 0, (1 | 2), 0)    # SHIFT
```

Therefore, the `_keyDown` and `_keyUp` functions could probably be modified to include the extended-key flag.

Also, the current online documentation for <a href="https://pyautogui.readthedocs.org/en/latest/msgbox.html">message box functions</a> includes <code>defaultValue</code> as an optional parameter when the functions actually accept <code>default</code> instead.

The page on <a href="https://pyautogui.readthedocs.org/en/latest/keyboard.html">keyboard control functions</a> explains that it's possible to pass a list of keys into <code>press()</code> but then gives an example where <code>keyDown()</code> receives the list <code>['left', 'left', 'left']</code>, which results in an AttributeError because it tries to use <code>.lower()</code> on the list.

I hope this submission is helpful!

**Comment by Chased1k** [comment]
Totally new to github, but I have to THANK YOU! for this submission.  helped me immensely.

**Comment by asweigart** [comment]
Closing this, as it seems fixed now. KEYEVENTF_EXTENDEDKEY seems to be used for simulating numpad keys. The documentation for pymsgbox has also been fixed by now. Thanks!
