### ISSUE TITLE
AttributeError: module 'pyautogui' has no attribute 'locateOnScreen' 

### ISSUE THREAD

**Issue by izzatz** [asweigart/pyautogui#152]
I'm having this no attribute error. I guess it break with pillow?

Python version = 3.6
pyautogui = 0.9.36
pillow = 4.1.1

**Comment by reaCodes** [comment]
@izzatz Any chance you have a file called `pyautogui.py` in the current working directory? Rename that (and delete a possibly existing `pyautogui.py` file

**Comment by izzatz** [comment]
@reaCodes hey that really works! It was my main demo file. I named it as pyautogui.py

**Comment by reaCodes** [comment]
Maybe you are a Python beginer. This is a mistake often made by beginners. Because I have made such a mistake, so I guess you may also have encountered this problem.

**Comment by izzatz** [comment]
I see. So the rule of thumbs you can't name your file same with your modules? TIL

**Comment by reaCodes** [comment]
Because when using `import` to import some packages or yourself module, Python always finds the file in the current directory. Then Python will import the `pyautogui.py` file which you wrote instead of `pyautogui.py` package.

**Comment by oscartrevio** [comment]
I'm new to programming and I am having the same problem.
I have searched for a file named `pyautogui.py` and can't find any.
What else could I do?

**Comment by anandjoseph70** [comment]
Yes, that worked very well but can you explain me how that is a bug or error..

**Comment by izzatz** [comment]
@oscartrevio and @anandjoseph70 

The rule of thumb in Python programming. You can't have the filename and import module with the same name. Unless you are going to import a specific file, not a module. 

@oscartrevio You wouldn't find it. pyautogui is the module name. It is not necessarily a physical file on your computer.
