### ISSUE TITLE
Hotkey functions are not working

### ISSUE THREAD

**Issue by chamithchathuka** [asweigart/pyautogui#159]
Hi,

hotkey functions is not working, in Python 3.4 for Windows 7 and Windows 8.1 64Bit
ex :-
 `pyautogui.hotkey('ctrl', 'a')`

not responding or no actions actions available for this issue

only the hot key function is not working all other keyboard control functions are working as expected.

**Comment by asweigart** [comment]
Duplicate of issue 158
