### ISSUE TITLE
KeyError: 'DISPLAY' when installing pyautogui

### ISSUE THREAD

**Issue by curkychen** [asweigart/pyautogui#161]
When I tried to install pyautogui with ` sudo pip3 install pyautogui`
I get the error info

 pi@raspberrypi:~/Desktop/test/c_test $ sudo pip3 install pyautogui
Downloading/unpacking pyautogui
  Downloading PyAutoGUI-0.9.36.tar.gz (46kB): 46kB downloaded
  Running setup.py (path:/tmp/pip-build-tbxln81q/pyautogui/setup.py) egg_info for package pyautogui
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-tbxln81q/pyautogui/setup.py", line 6, in <module>
        version=__import__('pyautogui').__version__,
      File "/tmp/pip-build-tbxln81q/pyautogui/pyautogui/__init__.py", line 115, in <module>
        from . import _pyautogui_x11 as platformModule
      File "/tmp/pip-build-tbxln81q/pyautogui/pyautogui/_pyautogui_x11.py", line 160, in <module>
        _display = Display(os.environ['DISPLAY'])
      File "/usr/lib/python3.4/os.py", line 633, in __getitem__
        raise KeyError(key) from None
    KeyError: 'DISPLAY'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-tbxln81q/pyautogui/setup.py", line 6, in <module>

    version=__import__('pyautogui').__version__,

  File "/tmp/pip-build-tbxln81q/pyautogui/pyautogui/__init__.py", line 115, in <module>

    from . import _pyautogui_x11 as platformModule

  File "/tmp/pip-build-tbxln81q/pyautogui/pyautogui/_pyautogui_x11.py", line 160, in <module>

    _display = Display(os.environ['DISPLAY'])

  File "/usr/lib/python3.4/os.py", line 633, in __getitem__

    raise KeyError(key) from None

KeyError: 'DISPLAY'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-tbxln81q/pyautogui
Storing debug log for failure in /root/.pip/pip.log

I followed the install steps listed in the Docs(http://pyautogui.readthedocs.io/en/latest/install.html). Do anyone know why this happens and how to fix it? Thank you so much.

**Comment by curkychen** [comment]
Have solved it. It is because of using ssh to install the package. When I install it by using the raspberrypi directly it solved.

**Comment by arbazkiraak** [comment]
Thankew @curkychen

**Comment by bit4woo** [comment]
is that mean must install on local server with GUI?

if I use a remote server and no GUI, installation will fail ?

**Comment by fandom16** [comment]
Exactly.

**Comment by louis030195** [comment]
Same problem when building docker image that use pyautogui

```
# Use an official Python runtime as a parent image
FROM python:2.7-slim

COPY requirements.txt ~/desktop/app/

# Set the working directory to /app
WORKDIR ~/desktop/app/

# Copy the current directory contents into the container at /app
ADD . ~/desktop/app/

# Because of pyautogui error
# RUN pip install python3_xlib

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt 
# Error here when have to install pyautogui
```

Any solution ?

**Comment by Habeen-Jun** [comment]
> is that mean must install on local server with GUI?
> 
> if I use a remote server and no GUI, installation will fail ?

so is there any method to install pyautogui with no error using a remote server and no GUI??

**Comment by tomhallio** [comment]
> so is there any method to install pyautogui with no error using a remote server and no GUI??

Did you find out if there was a way to do it through SSH (no GUI, remote server)?

**Comment by MCOfficer** [comment]
> 
> 
> > so is there any method to install pyautogui with no error using a remote server and no GUI??
> 
> Did you find out if there was a way to do it through SSH (no GUI, remote server)?

i remember being able to do it following the SO question i linked.

**Comment by JeedHome44** [comment]
Hello,

I do a mouse-reset.py like this for my magic mirror:


```
#!/usr/bin/python3
# -*- coding: utf-8 -*-

import pyautogui
import time

while True:
    try:
        if pyautogui.position != (1918, 1078):
            time.sleep(0.1)
            pyautogui.moveTo(1918, 1078)
            time.sleep(0.1)
        time.sleep(0.1)
    except:
        time.sleep(0.1)

```

it's work correctly when the mirror boot. but i need to pkill puthon when i want to power off the screen.

my problem: i can't laucnh this in SSH: python3 /home/pi/programmes/mouse-reset.py

i have error display.

pyautogui test the client but not serveur display.

What i have to do to do this python program in SSH?

i test add it in a mouse.sh and do: bash /home/pi/scripts/mouse.sh but same problem: Error Display.

Please, i need help to activate this python program with SSH when i do bash /home/pi/scripts/ecran_on.sh

thank you for your help.

**Comment by SaD-Pr0gEr** [comment]
нкш   6ьшшшшшшш5ератглвлл

**Comment by SaD-Pr0gEr** [comment]
44тт6цогненрпрп

**Comment by SaD-Pr0gEr** [comment]
ллллллллллллллллллллллллллллллллллллллллллллллллллллллллллллллллллллллллллллллллллллллллл
