### ISSUE TITLE
Add menu key

### ISSUE THREAD

**Issue by i-need-to-tell-you-something** [asweigart/pyautogui#164]
This is a feature request, but i could find how I could tag it as such.

[Menu key](https://en.wikipedia.org/wiki/Menu_key) would be quite useful for GUI automation I believe. Luckily I found a workaround: it turns out at least some applications support Shift + F10 as an alternative.

**Comment by hugoesb** [comment]
Try "super" or "win":

`pyautogui.press('super')`

**Comment by i-need-to-tell-you-something** [comment]
Im pretty sure Windows/Super/Meta is a different button than the one I mean. If you could check out the Wikipedia link I provided then maybe you'll understand. An image search would also mostly return the correct item.

**Comment by hugoesb** [comment]
I see. In fact, when you send some "press" the OS receive a hexadecimal. We can see a list of hexa in this website: http://msdn.microsoft.com/en-us/library/windows/desktop/dd375731(v=vs.85).aspx

I suppose you want to send the "0xA4". If you read the "_pyautogui_win.py" file from pyautogui you findout you can send "0xA4" using:

`pyautogui.press('altleft')'

If you wish you can suggest modify the "_pyautogui_win.py" code  inserting in `keyboardMapping` dictionary the key `'menu': 0xa4, # VK_LMENU`

**Comment by i-need-to-tell-you-something** [comment]
It was 0x5D that I meant. Ah I figured it out. The problem was in _pyautogui_x11.py. Wrong string there for the 'apps'. Thanks for pointing the direction. It helped a lot. ^_^

**Comment by i-need-to-tell-you-something** [comment]
I also submitted a pull request with the minor fix.

**Comment by asweigart** [comment]
Fixed in PR 172. Thanks!

**Comment by i-need-to-tell-you-something** [comment]
Thank you for the rest of the software and project management and for looking at the PR!
