### ISSUE TITLE
Tkinter application Quit Error while using Pyautogui

### ISSUE THREAD

**Issue by sumitchawla27** [asweigart/pyautogui#166]
I am using pyautogui in one of the scripts and receiving below error:
I think the error is something related to Tkinter (used in Pyautogui package) or in Tkinter Application Quit code.
Error - can't invoke "winfo" command: application has been destroyed
    while executing
"winfo exists $w"
    (procedure "::tk::ButtonInvokeEnd" line 2)
    invoked from within
"::tk::ButtonInvokeEnd .!frame4.!button normal raised"
    ("after" script)

Script  is working fine on some systems but not on one.
Can you please help me on this and tell me what could be the reason for this error.
What should I check on that particular system?
Quick response will be very helpful. Thanks in advance.

**Comment by asweigart** [comment]
Sorry for the delay in responding.

Without more exact repro steps, I can't do much with this issue. I'm fairly certain that this is a tkinter issue, rather than an issue with pyautogui.
