### ISSUE TITLE
How to install Pyautogui in Ubuntu using conda?

### ISSUE THREAD

**Issue by s1291** [asweigart/pyautogui#167]
I have installed pyautogui in my Ubuntu machine using `pip3`.
Now I have `conda` I cannot figure out how to install `pyautogui` using it.

Any help please.

**Comment by hugoesb** [comment]
I'm using Anaconda on Windows and I can say that Anaconda don't have pyautogui in repository. In Windows I installed pyautogui using pip and it is everything working ok.

Try use the pip that 
is installed inside the "Scripts" folder in conda directory.

**Comment by Samir-ouchene** [comment]
@hugoesb Thank you, Actually that works but before doing that we have to `pip install python3_xlib`.
