### ISSUE TITLE
Suggesstion: Rewrite the LocateOnScreen function with python-opencv

### ISSUE THREAD

**Issue by ty-me** [asweigart/pyautogui#168]
The  function `LocateOnScreen` not works perfectly sometimes so I  rewrite this function with python-opencv lib  in my private project.

Docs about `Template Matching`: http://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_imgproc/py_template_matching/py_template_matching.html#template-matching-with-multiple-objects

code:

```
def locate_on_screen(tpl_path):
    screenshot_img = 'locate_on_screen_image_{}.png'.format(time.time())
    gui.screenshot('/tmp/{}'.format(screenshot_img))

    img_rgb = cv2.imread('/tmp/{}'.format(screenshot_img))
    img_gray = cv2.cvtColor(img_rgb, cv2.COLOR_BGR2GRAY)
    template = cv2.imread(tpl_path, 0)
    w, h = template.shape[::-1]
    res = cv2.matchTemplate(img_gray,template,cv2.TM_CCOEFF_NORMED)
    threshold = 0.8
    loc = np.where( res >= threshold)

    # debug
    for pt in zip(*loc[::-1]):
        return (pt[0], pt[1],  w , h)

    return False
```

**Comment by mythnc** [comment]
Hi @ty-me , Thanks for your sharing.
I just found the original source code already consider the situation of using opencv.

Maybe you would like to take a look:
https://github.com/asweigart/pyscreeze/blob/b6242c0402d99ad17d3f0201741b02441728d418/pyscreeze/__init__.py#L450

**Comment by asweigart** [comment]
This feature has been implemented! Thanks!
