### ISSUE TITLE
how to open a program as administrator in windows

### ISSUE THREAD

**Issue by Rafi993** [asweigart/pyautogui#185]
I have been trying to open a program as administrator I even tried right click but it does not seem to work any idea how to proceed

**Comment by Py-king** [comment]
Using the subprocess module should do the trick.
import subprocess
subprocess.call(['runas', '/user:Administrator', 'path_to_program.exe'])

**Comment by Rafi993** [comment]
hope this could be added to docs too for future reference of others.

**Comment by Rafi993** [comment]
I have added this to cheat sheet and gave a pull request for future reference of others  https://github.com/asweigart/pyautogui/pull/190
