### ISSUE TITLE
_locateAll_python() got an unexpected keyword argument 'confidence'

### ISSUE THREAD

**Issue by aj22r** [asweigart/pyautogui#189]
When i use `pyautogui.locateCenterOnScreen("a.png", confidence=.9)` on my PC it works just fine, but when i use the exact same command on my laptop it won't work and gives the error in the title. I did `pip install pyautogui` on both machines, does anybody know how to fix that?

**Comment by mythnc** [comment]
I guess your have `opencv3.0+` and `python3` installed in your PC, so you could use `confidence` parameter. 
By contrast, there are no either `opencv3.0+` or `python3` in your laptop, so `pyscreeze` package has to call `_locateAll_python` instead of `_locateAll_opencv`, and there is no `confidence` parameter in `_locateAll_opencv`.

**Comment by amrit851** [comment]
@mythnc  I have opencv (3.4.3) and python(3.4). My code works fine when I run it from command line. But when I packaged the code with py2exe and ran the exe created, the same error came:-

> When i use `pyautogui.locateCenterOnScreen("a.png", confidence=.9)` on my PC it works just fine, but when i use the exact same command on my laptop it won't work and gives the error in the title. I did `pip install pyautogui` on both machines, does anybody know how to fix that?

**Comment by hernandik** [comment]
I stump exactly over the same problem.
Does anyone have a solution?

**Comment by deimosfr** [comment]
Same for me

**Comment by deimosfr** [comment]
Fixed the issue with opencv-python module installed

**Comment by okadath** [comment]
it is necessary to install the python open-cv library in order to handle the "confidence" attribute, without this it works but without the value of  "confidence"

**Comment by asweigart** [comment]
This will be fixed in version 0.1.27 by providing a better error message if opencv isn't installed and a confidence keyword argument is provided.

**Comment by Misnad** [comment]
I have open-cv installed and I still get the error.

**Comment by lingyuncelia** [comment]
I have the same problem.

**Comment by JayRizzo** [comment]
Hi all,

I am not sure if this is still an issue, but did you try updating the package?

`pip install opencv-python` or `pip3 install opencv-python`

https://stackoverflow.com/a/57833155/1896134

You can also try as noted on another similar question:

`pip install numpy==1.15.2` or `pip3 install numpy==1.15.2`

https://stackoverflow.com/a/64848438/1896134


I don't have an issue with this code.

# Example:

```python
# Import needed modules
import os
import pyautogui

# Set the file name for the example screenshot
filename = 'test.png'

print("Current working directory: {0}".format(os.getcwd()))

# Change the current working directory to home
current_home = os.path.expanduser('~')
os.chdir(current_home)

# Print the current working directory
print("Current working directory: {0}".format(os.getcwd()))

# Take a Screenshot of small part of your main screen.
im1 = pyautogui.screenshot(region=(150,150, 200, 200))
# Save the Screenshot save it to the file name.
im1.save(filename)

# Set the current path
current_path = os.path.realpath('.')
# Set the current path to the file
path_to_file = os.path.join(current_path, filename)

# Set an image counter
x = 0

# Set the current path and if the file exists
if os.path.exists(path_to_file):
    for pos in pyautogui.locateAllOnScreen(path_to_file, grayscale=False, confidence=0.95):
        x += 1
        print("Locations of image {} found: {}".format(x, pos))
    print('Successful # Of Images Found Were: {}'.format(x))
else:
    print('Failed to locate Image.  Image Not Found At: {}'.format(path_to_file))

```

# Results
```
Locations of image 1 found: Box(left=150, top=147, width=200, height=200)
Locations of image 2 found: Box(left=149, top=148, width=200, height=200)
Locations of image 3 found: Box(left=150, top=148, width=200, height=200)
Locations of image 4 found: Box(left=151, top=148, width=200, height=200)
Locations of image 5 found: Box(left=148, top=149, width=200, height=200)
Locations of image 6 found: Box(left=149, top=149, width=200, height=200)
Locations of image 7 found: Box(left=150, top=149, width=200, height=200)
Locations of image 8 found: Box(left=151, top=149, width=200, height=200)
Locations of image 9 found: Box(left=152, top=149, width=200, height=200)
Locations of image 10 found: Box(left=147, top=150, width=200, height=200)
Locations of image 11 found: Box(left=148, top=150, width=200, height=200)
Locations of image 12 found: Box(left=149, top=150, width=200, height=200)
Locations of image 13 found: Box(left=150, top=150, width=200, height=200)
Locations of image 14 found: Box(left=151, top=150, width=200, height=200)
Locations of image 15 found: Box(left=152, top=150, width=200, height=200)
Locations of image 16 found: Box(left=153, top=150, width=200, height=200)
Locations of image 17 found: Box(left=148, top=151, width=200, height=200)
Locations of image 18 found: Box(left=149, top=151, width=200, height=200)
Locations of image 19 found: Box(left=150, top=151, width=200, height=200)
Locations of image 20 found: Box(left=151, top=151, width=200, height=200)
Locations of image 21 found: Box(left=152, top=151, width=200, height=200)
Locations of image 22 found: Box(left=149, top=152, width=200, height=200)
Locations of image 23 found: Box(left=150, top=152, width=200, height=200)
Locations of image 24 found: Box(left=151, top=152, width=200, height=200)
Locations of image 25 found: Box(left=150, top=153, width=200, height=200)
Successful # Of Images Found Were: 25

OR if nothing is found.

Successful # Of Images Found Were: 0

```

# Note:
There looks to be a *MAX* of 10,000 images, if it finds more than that.

```
Locations of image 9998 found: Box(left=442, top=5, width=10, height=10)
Locations of image 9999 found: Box(left=443, top=5, width=10, height=10)
Locations of image 10000 found: Box(left=444, top=5, width=10, height=10)
Successful # Of Images Found Were: 10000
```

Hope this helps!

**Comment by Morty235** [comment]
> I have open-cv installed and I still get the error.

have you solved this problem?
