### ISSUE TITLE
pyautogui doubleclick() not working on OSX 

### ISSUE THREAD

**Issue by bobsdavenport** [asweigart/pyautogui#194]
pyautogui.doubleClick() appears ineffective even though item has focus etc.

pyautogui.click(clicks='2', interval=0.5) and alike also ineffective
as above the folder has focus [via pyautoguiclick()] so would be interested for help in why the function doesn't work on OSX

unfortunately

re downloading newest version of pyautogui is problematic too
the setup.py fails.
presumably i need to copy the files manually [not a good idea]

**Comment by albertovilva** [comment]
Same experience on MacOS Sierra 10.12.3.

If I place a moveTo() after click() the click won't even work.

**Comment by devnowcommit** [comment]
Any news on this? I've tried to double click a pdf in finder and I realized that after doubleclick it gets to change the name. So it seems that it's doing two clicks but far away in time from one to another. Any suggestions? I've tried setting parameters like: pyautogui.click(310, 494, 2, 0.00001, 'left') and still nothing. PLEASE HELP!

**Comment by joaquindev** [comment]
I've solved it using pynput

**Comment by JayRizzo** [comment]
I know this has been a minute but have a look at my PR and let me know flipping these two lines have helped fix this issue for you as it has on my machine.

* @bobsdavenport @vilvadot @devnowcommit

**Comment by mrmillmill** [comment]
@JayRizzo is correct on his solution for me! I used the following to select current window for excell then doubleclick a field in an excel sheet:
`pyautogui.click()`
`pyautogui.sleep(2)`
`pyautogui.click(clicks=2, interval=0.15)`
`pyautogui.doubleClick()`

...where the pyautogui.click() serves as selecting my current window. Then the pyautogui.click(clicks=2, interval=0.15) selects my current cell within excell sheet and finally the pyautogui.doubleClick() serves as my doubleClick on the cell to put it in edit mode. Hope this helps someone else in the web-uh-verse.
