### ISSUE TITLE
Python3?

### ISSUE THREAD

**Issue by codewriter4** [asweigart/pyautogui#205]
Any Python3 compatibility?

**Comment by linusg** [comment]
Of course it runs under Python 3, why not? Have you even tried?

**Comment by Mardox91** [comment]
I've been using it on python3 and it works.

**Comment by Blucknote** [comment]
runing on python3 fine

**Comment by vikramdurai** [comment]
@codewriter the general consensus seems to be that the issue is resolved, you should close the issue.

**Comment by afs2015** [comment]
@asweigart: I believe this can be marked as closed. Should we add to the documentation that this project supports both Python 2 and Python 3?

**Comment by asweigart** [comment]
Yes, we should note that in the documentation that PyAutoGUI is for both Pytho n2 and 3.
