### ISSUE TITLE
pyautogui import crashing python

### ISSUE THREAD

**Issue by YashKumarVerma** [asweigart/pyautogui#218]
Rest everything works fine with python except **pyautogui**

![screenshot 327](https://user-images.githubusercontent.com/14032427/38176360-ff689276-360a-11e8-9fa5-1493bc7f8439.png)

Python 3.6.0 :: Anaconda 4.3.1 (64 Bit)
Tried reinstalling both, python and pyautogui but nothing worked.

**Comment by neeksor** [comment]
I installed https://www.python.org/downloads/release/python-365/  on windows 10. pyautogui works fine for me.

**Comment by YashKumarVerma** [comment]
I figure it out. I had anaconda installed, which somehow is ***not at ease*** with pyautogui. Switching from the anaconda bundle of python to a clean vanilla install worked.
