### ISSUE TITLE
locateOnScreen doesn't work

### ISSUE THREAD

**Issue by DamonSnow** [asweigart/pyautogui#220]
i try to use this function,but always return none, my OS is Win10, python 3.6.2

**Comment by DamonSnow** [comment]
plus,  locateOnScreen function works right in Win7

**Comment by Zorg-xx** [comment]
hi, 
I have the same problem on my linux.
To bypass this problem i use :
pyautogui.LocateOnScreen('img.png',grayscale=True)

**Comment by global2alex** [comment]
I don't have your code but, could this possibly be because of transparency in windows? @asweigart
