### ISSUE TITLE
Can not install because readme not found

### ISSUE THREAD

**Issue by BWBama85** [asweigart/pyautogui#245]
`    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\bamas\AppData\Local\Temp\pip-install-bqja5nj7\pyscreeze\setup.py", line 10, in <module>
        with open("README.md", "r") as fh:
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'`

**Comment by zerocewl** [comment]
The new release of pyscreeze fails to install.

As workaround try:

`pip install pyscreeze==0.1.14`

I created a new ticket for this issue too.
https://github.com/asweigart/pyscreeze/issues/37

**Comment by reaCodes** [comment]
I can't install pyautogui and pyscreeze
![image](https://user-images.githubusercontent.com/13817254/42950408-8719e594-8ba6-11e8-8710-282d44d4d65c.png)

**Comment by vince-wu** [comment]
Also having same problem.

![image](https://user-images.githubusercontent.com/20054326/42963328-c60b5d7c-8b48-11e8-94a0-40df8192b230.png)

**Comment by zerocewl** [comment]
For me, the error is gone with the closed ticket asweigart/pyscreeze#37 and the new version of pyscreeze 0.1.18.

**Comment by reaCodes** [comment]
I can install pyscreeze, but still can't install pyautogui

**Comment by asweigart** [comment]
Fixed as of (and sometime before) 0.9.38.
