### ISSUE TITLE
Pyautogui doesn't seem to work on macOS Mojave

### ISSUE THREAD

**Issue by chaityacshah** [asweigart/pyautogui#247]
I recently updated to macOS Mojave (10.14 Beta). Commands like `pyautogui.moveTo(1027,73)`, `pyautogui.click(1027,73)`, etc. don't seem to work at all. Neither any error messages are thrown nor do the method calls work. pyautogui worked perfectly on macOS High Sierra.

**Comment by Shark4109** [comment]
I have exactly the same issue, no errors whatsoever, Also tried with different python libraries and mouse move doesn't seem to work on macOS Mojave. Mouse location does work tho. I also managed to move mouse with Cocoa, so I guess event names or something must have been changed. As I looked a bit, there might be some issues with pyobjc not being fully optimized for macOS Mojave.

**Comment by cyril94440** [comment]
Same issue here !

**Comment by Shark4109** [comment]
I managed to solve the mouse moving with Quartz library (which pyautogui uses), but doing clicks seems to be much harder.

**Comment by joshua-robinson** [comment]
Any news on fixing this?

**Comment by DimitriosLisenko** [comment]
Not a pyautogui user, but on Mojave, there's a new security feature where you must explicitly allow applications to use your mouse/keyboard. Have a look in Security Preferences > Security & Privacy > Privacy > Accessibility - you might have to allow your terminal application in the list.

**Comment by Shark4109** [comment]
@DimitriosLisenko You are right! This actually worked, personally I'm using iTerm so I had to add it in Accessibility as you described!

**Comment by chaityacshah** [comment]
@DimitriosLisenko - Thank You!  This fixed the issue so closing it.

**Comment by tros897** [comment]
@DimitriosLisenko I have allowed my application in the list, but it does not work for me.

**Comment by Shark4109** [comment]
@tros897 Whit what application you are running python script? I was using iTerm2, so I had to add this to application list, make sure you add the correct application.

**Comment by tros897** [comment]
@Shark4109 I try to learn how to build a python bot to play a simple game, and I'm running python script in Pycharm. I add Pycharm to application list,  but it's not working.

**Comment by jzxyryz** [comment]
> @Shark4109 I try to learn how to build a python bot to play a simple game, and I'm running python script in Pycharm. I add Pycharm to application list, but it's not working.

Try to add Python Launcher (/Applications/Python 3.7/) in that app list.

**Comment by SarthakDandriyal** [comment]
Is there any alternate library which we can use on mac

**Comment by Nv7-GitHub** [comment]
Thank you, the python launcher needed to be added

**Comment by tajalagawani** [comment]
Any news on fixing this? I'm having the same issue on Mojave.

**Comment by Shark4109** [comment]
> 
> 
> Any news on fixing this? I'm having the same issue on Mojave.

The issue was already resolved. Since Mojave OS you need to add permissions to python to accessibility. Read the comment from @DimitriosLisenko.

**Comment by petyaracz** [comment]
Same issue under mojave, pyautogui moves mouse but doesn't, specifically, left click. Added python launcher, terminal app, IDLE to apps that can control computer. No change.

**Comment by spiladon** [comment]
[This](https://stackoverflow.com/a/58087573/9887890) answer helped with left click on MacOS10.13.6 HS.

**Comment by eddjimlab** [comment]
This works fine for me.
You have to install another library pynput

from pynput.mouse import Listener, Controller, Button

mouse = Controller()

pyautogui.moveTo(x, y)
mouse.click(Button.left, 2)

**Comment by ii0** [comment]
> Not a pyautogui user, but on Mojave, there's a new security feature where you must explicitly allow applications to use your mouse/keyboard. Have a look in Security Preferences > Security & Privacy > Privacy > Accessibility - you might have to allow your terminal application in the list.

thanks a lot, u R hero

**Comment by angelplata** [comment]
In MAC with Ventura and Visual Studio Code just Preferences > Security & Privacy > Privacy > Accessibility  and allow Visual Studio Code to control your computer, it worked great for me
