### ISSUE TITLE
I can't stop the loop

### ISSUE THREAD

**Issue by jerb6** [asweigart/pyautogui#253]
Hello ! 
Here is my problem, I try to loop a "find and click" on a specific image ( the "NON" button ), it works but the loop don't stop when all the images are clicked...
How can I tell him that when there's no image left he stop the loop and continu with the code ?

here's my code : 

<img width="717" alt="capture d ecran 2018-08-18 a 17 31 54" src="https://user-images.githubusercontent.com/42121527/44300763-a51ee300-a30c-11e8-9087-e25688022f11.png">

here's the image : 

<img width="218" alt="capture d ecran 2018-08-18 a 17 30 12" src="https://user-images.githubusercontent.com/42121527/44300744-7274ea80-a30c-11e8-976a-cd7181afc3a0.png">

Can someone help me please ?
Thank you !

**Comment by leonstafford** [comment]
according to the docs, the `locateOnScreen` returns a `ImageNotFoundException`, so may be similar for your `locateCenterOnScreen`. In which case, perhaps a Try.. Catch block, so you can handle the exception when no more image matches?

An idea only, I'm just starting to look at this project
