### ISSUE TITLE
AttributeError: module 'pyautogui' has no attribute 'locateAllOnScreen'

### ISSUE THREAD

**Issue by FarhanRehman** [asweigart/pyautogui#258]
i get this error"AttributeError: module 'pyautogui' has no attribute 'locateAllOnScreen'"
my code:

import pyautogui

for restart in pyautogui.locateAllOnScreen('image.png'):
    print(restart)

**Comment by mikebvansickle** [comment]
@FarhanRehman If you could provide any details about what you're running on then that would help a lot. Python version, pyautogui version, operating system, etc.

For what it's worth on Windows 10, Python 3.7.1, and pyautogui 0.9.38 in virtualenv I haven't been able to replicate this error.
