### ISSUE TITLE
Hotkeys in remote desktop

### ISSUE THREAD

**Issue by SimoneS93** [asweigart/pyautogui#28]
I'm having troubles trying to copy text from a remote desktop window and pating in a local text editor. Can this library handle this?
I found it doesn't even handle any keyboard method on the remote desktop.

**Comment by asweigart** [comment]
Are you talking about the Remote Desktop Connection program that comes with Windows? I haven't tested this with that (or any other remote desktop software). I'll leave this issue open as a reminder, but I currently don't have time to investigate this. Thanks for bringing it up though.

**Comment by asweigart** [comment]
Currently PyAutoGUI doesn't support remote/headless machines. I've created a master issue #133 to track the development of this feature.
