### ISSUE TITLE
Error in wiki about key word confidence in function locateOnScreen

### ISSUE THREAD

**Issue by wtysos11** [asweigart/pyautogui#297]
In the english [wiki](https://pyautogui.readthedocs.io/en/latest/screenshot.html),it said there's a key word in function locateOnScreen named confidance. So the usage of this function can be `button7location = pyautogui.locateOnScreen('calc7key.png', confidence=0.9)`.

But in the file `pyautogui/screenshotUtil.py`, the function is `locateOnScreen(image, grayscale=False,region=None):`, and of course I can't use such a key word.

**Comment by aptrades** [comment]
I installed **opencv_contrib_python-4.1.1.26-cp35-cp35m-win_amd64** with **python 3.5.**
Then i import numpy,pyautogui,cv2 and use the command :
pyautogui.click('st.png',confidence=0.9) 

i get the following error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: click() got an unexpected keyword argument 'confidence'

Please help.

**Comment by piningforfjords** [comment]
Same here.

**Comment by nesttle** [comment]
Same here
