### ISSUE TITLE
Windows Calcuator doesn't seem to receive "mouse move" message.

### ISSUE THREAD

**Issue by asweigart** [asweigart/pyautogui#314]
A reader brought this up in an email to me. When PyAutoGUI moves the mouse over the Windows calculator app, the button doesn't seem to highlight the way it does when you manually move the mouse over it. I'm not sure if this is limited to the calculator app or to all Windows programs, but it deserves further investigation.

**Comment by DataSolveProblems** [comment]
I have experiencing the same issue as well.

**Comment by Ved-C7** [comment]
Was this issue fixed?
