### ISSUE TITLE
How can I get window hwnd?

### ISSUE THREAD

**Issue by JackyNiu** [asweigart/pyautogui#319]
I want get window hwnd,what should I do?

**Comment by 2017jw** [comment]
refer to pygetwindow

**Comment by JackyNiu** [comment]
I have been use method find_windows from pywinauto to solve my problem.

**Comment by asweigart** [comment]
You can get the window object by calling, say, pyautogui.getAllTitles() and then access the _hWnd attribute to get the window handle. This isn't a publicly supported attribute though, and may change in the future (hence the leading underscore in the name.)
