### ISSUE TITLE
Windows: if you remote desktop into the PC and exit the remote session, pyautogui doesnt work

### ISSUE THREAD

**Issue by riz-hossain** [asweigart/pyautogui#34]
Steps to reproduce:
- have a script running that uses pyautogui 
- from a different PC remote into the pc that is running pyautogui
- Exit remote desktop 

Expected:
- pyautogui would continue to work as expected
  Actual:
- gives error "Error Message: PyAutoGUI fail-safe triggered from mouse moving to upper-left corner. To disable this fail-safe, set pyautogui.FAILSAFE to False.;"

Additional Note:
- if i set it, to False, I get permission error when trying to call click function.
- If i simply log in physically to the machine that is running pyautogui, everything starts to work

**Comment by peterjkrey** [comment]
I fixed this by launching a 2nd windows machine on a cloud, and it is permanently running and logged in by RDP to the 1st windows machine, which is running my pyautogui script. Its not a beautiful fix, but gets the job done.

**Comment by thaffenden** [comment]
I know this issue was raised a while ago, but I had the same issue previously so thought I'd add how I worked around it.
### The Issue
The root cause of this is because windows stops outputting the display when you exit the remote desktop session (I'd assume to save memory or something). Because the remote PC is no longer outputting a display, PyAutoGUI has nothing to actualy interact with.
### A solution
Use a remote desktop client that allows you to keep outputting the display, even if you minimise the window/close your PC. I used terminals (https://terminals.codeplex.com/ - not affiliated with them at all just recommending as it solved this issue for me).You can set this up to persist the display, and your code should then run fine. 

I'd say this issue should be closed, as I don't believe there is a way PyAutoGUI would be able to handle this.

**Comment by asweigart** [comment]
Currently PyAutoGUI doesn't support remote/headless machines. I've created a master issue #133 to track the development of this feature.

**Comment by hernanigil** [comment]
you can use pyvncdotool. I used this together with cv2 modules. I connect to x11vnc server using the pyvncdotool, capture the screen. Cv2 allows me to find the buttons I want to press giving me it's coordinates. this is the way I worked this around.

**Comment by gumihosystem** [comment]
when you disconnect from RDP, Windows lock the computer and does not render the screen any more so any automation apps which needs GUI fails to work. To disconnect from RDP without losing the screen you can disconnect using following commands as administrator (its better to make a bat file and run that file as administrator when you need to disconnect from RDP):


**for /f "skip=1 tokens=3" %%s in ('query user %USERNAME%') do (
 %windir%\System32\tscon.exe %%s /dest:console )**

from https://stackoverflow.com/questions/56949942/pyautogui-on-rdp

**Comment by tilefishpoele** [comment]
> I know this issue was raised a while ago, but I had the same issue previously so thought I'd add how I worked around it.
> 
> ### The Issue
> The root cause of this is because windows stops outputting the display when you exit the remote desktop session (I'd assume to save memory or something). Because the remote PC is no longer outputting a display, PyAutoGUI has nothing to actualy interact with.
> 
> ### A solution
> Use a remote desktop client that allows you to keep outputting the display, even if you minimise the window/close your PC. I used terminals (https://terminals.codeplex.com/ - not affiliated with them at all just recommending as it solved this issue for me).You can set this up to persist the display, and your code should then run fine.
> 
> I'd say this issue should be closed, as I don't believe there is a way PyAutoGUI would be able to handle this.

Is that not really the problem as you can edit the registry subkeys to stop this from happening as per?: https://community.helpsystems.com/kb-nav/kb-article/?id=548d72cc-68c3-eb11-bacc-000d3a1fe4c0&redirect=false

**Comment by Abhishek-soni1** [comment]
Try this, and please let me know if this works:
https://support.smartbear.com/testcomplete/docs/testing-with/running/via-rdp/in-minimized-window.html

**Comment by leandro518** [comment]
> Try this, and please let me know if this works: https://support.smartbear.com/testcomplete/docs/testing-with/running/via-rdp/in-minimized-window.html

Tks man, works for me
