### ISSUE TITLE
How can I use the functions those control windows

### ISSUE THREAD

**Issue by ClericPy** [asweigart/pyautogui#35]
such like  activate window and move window 
 autohotkey has these methods ,
WinActivate, [ WinTitle, WinText, ExcludeTitle, ExcludeText]
WinWait, WinTitle, WinText, Seconds [, ExcludeTitle, ExcludeText]

can pyautogui support background operation？

**Comment by asweigart** [comment]
There isn't a way to do it currently, though AutoHotkey's set of features is stuff I'd like to see in PyAutoGUI. Currently, you can activate a window by simulating a click on it.
