### ISSUE TITLE
Command gets executed instead of assignment

### ISSUE THREAD

**Issue by antchal** [asweigart/pyautogui#354]
I defined two variables as:
` switchWindow = pyautogui.keyDown('alt'); pyautogui.press('tab'); pyautogui.keyUp('alt') `
` paste        = pyautogui.keyDown('ctrl'); pyautogui.press('v'); pyautogui.keyUp('ctrl')`

but the commands get executed right at the assignment step and nowhere else thereafter.

**Comment by amenat** [comment]
AFAIK python doesn't work like that. If you need to call switchWindow from code again and again, you need to define a function.

```python
def swtichWindow():
    pyautogui.keyDown('alt')
    pyautogui.press('tab')
    pyautogui.keyDown('alt')
```

then call `switchWindow()` from your code whenever you want to perform these series of actions. 

This is not a bug. so issue can be closed.
