### ISSUE TITLE
Click Intervals on Mac not working properly

### ISSUE THREAD

**Issue by UkwaA** [asweigart/pyautogui#369]
I'm running Mac OS Mojave and when trying to use the click function with an intervals argument it seems like the intervals aren't working. According to the documentation's example, an interval of .25 is a quarter of a second, but when I put 10 in to represent 10 seconds all of the clicks still seemed to happen instantaneously. I even tried 100000 just to see if I was misinterpreting but they still happened instantaneously. Is anyone else having this problem on Mac?

**Comment by JayRizzo** [comment]
I have this issue as well on Mac OS Mojave 10.14.6 for over a month now.
I cannot figure out why as there is no issues or warnings in my terminal as I test it.

    from pyautogui import click
    click(clicks=2, interval=0.25)
 
Behaves the same way as

    from pyautogui import click
    click(clicks=2000, interval=0.25)
 
I have tried 

- running as my `logged in user`
- running as my `sudo su`
- running in a freshly created `venv`
- running a previous versions of `pyautogui`
- running on `'2.7.16 (default, Apr 12 2019, 15:32:40) \n[GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.3)]'`
- running on `sys.version '3.7.4 (default, Jul  9 2019, 18:13:23) \n[Clang 10.0.1 (clang-1001.0.46.4)]'`

Currently Using:
- `PyAutoGUI 0.9.47`
- `pyobjc & pyobjc-core 5.2`

**Comment by JayRizzo** [comment]
So, **_I think I found the location of the culprit!_**  

This has been bothering me, so, I found a temporary work around for now, still looking into as to why...

Work around for `Mac OSX` is to install an earlier version.

    pip3 install 'pyautogui==0.9.44'

Something functionally broke in:

    pip3 install 'pyautogui>=0.9.45'

That caused this to happen.

**Comment by JayRizzo** [comment]
I believe this is the culprit: https://github.com/asweigart/pyautogui/commit/967bdc3d8d24ee4bf1e558b70d49a9d2dd4fe31e#r35260398

**Comment by UkwaA** [comment]
> So, **_I think I found the location of the culprit!_**
> 
> This has been bothering me, so, I found a temporary work around for now, still looking into as to why...
> 
> Work around for `Mac OSX` is to install an earlier version.
> 
> ```
> pip3 install 'pyautogui==0.9.44'
> ```
> 
> Something functionally broke in:
> 
> ```
> pip3 install 'pyautogui>=0.9.45'
> ```
> 
> That caused this to happen.
> 
> From the change log:
> [v0.9.45, 2019/06/18 -- Added left-click, made mouse buttons more explicit and fixed it so that the right mouse button is 2 and middle mouse button is 3. Added failsafe points in all corners. Added screenshot logging. Fixed _autoPause(). ](https://github.com/asweigart/pyautogui/blob/5a842d88ceaa217a9e48873405b0135bce60c938/CHANGES.txt#L2)
> 
> Looking deeper: I suspect it may be the changed file of `pyautogui/_pyautogui_osx.py` [in the 0.9.45 update.](https://github.com/asweigart/pyautogui/commit/967bdc3d8d24ee4bf1e558b70d49a9d2dd4fe31e#r35260056)

Your solution worked! Thank you very much.

**Comment by JayRizzo** [comment]
@UkwaA  I created a PR #375  that should fix this issue going forward.   Check out my code and let me know if it works for you too.

**Comment by asweigart** [comment]
Fixed by PR #375
