### ISSUE TITLE
Click on OSX is happening three times

### ISSUE THREAD

**Issue by JonKoser** [asweigart/pyautogui#370]
A single click on Mac OSX results in three very quick clicks.
The problem is line 510 in \_\_init\_\_.py where it is explicitly calling multiClick for a count of 3:
https://github.com/JonKoser/pyautogui/blob/bd5f3bfa7a4f035cf58d80033730c678b5b077d8/pyautogui/__init__.py#L510
``` python
    if sys.platform == 'darwin':
        platformModule._multiClick(x, y, button, 3)
```

**Comment by JayRizzo** [comment]
@JonKoser I noticed this a while back.  Please see my comments on #369, as I offer a temporary work around until this gets fixed (if desired).  

The secondary issue of the `click` functionality, is it no longer brings the clicked window into focus.  So, if your run your terminal window from either calling or directly in the python3 interpreter there is an issue where you can still type in terminal even if it is `click`'ing in another window.  Odd, but tied to the release change of `pyautogui>=0.9.45` where the behavior was explicitly changed for OSX.

Cheers,

Jay

**Comment by JonKoser** [comment]
So long as it's on your radar :)
In the meantime, I can use 0.9.44. Thanks!
