### ISSUE TITLE
click() method results in clicking 3 times (macOS Mojave)

### ISSUE THREAD

**Issue by tsiaGeorge** [asweigart/pyautogui#383]
There is a bug when using the click() method which results in clicking 3 times. 

By looking at the code base there is a condition which calls the _multiclick function:
https://github.com/asweigart/pyautogui/blob/737192e18878aa81d922b592c99e32073aee0f54/pyautogui/__init__.py#L993-L994

Bellow is the implementation of _multiclick function:
https://github.com/asweigart/pyautogui/blob/737192e18878aa81d922b592c99e32073aee0f54/pyautogui/_pyautogui_osx.py#L390-L420

**Comment by JayRizzo** [comment]
Hi @tsiaGeorge, Yes this is a known issue.  Mentioned in #369 #370 please [see my workaround](https://github.com/asweigart/pyautogui/issues/369#issuecomment-535804275) until this is resolved.  

I have an open PR #375 https://github.com/asweigart/pyautogui/pull/375 to fix this but, no traction yet.  Please either checkout my branch that works as my interpretation of "Intended" or use my workaround.  

Thanks!

**Comment by tsiaGeorge** [comment]
thanks for the info. Cheers!

**Comment by asweigart** [comment]
Fixed by PR #375

**Comment by capitanbarbosa** [comment]
The same is happening to me on windows

**Comment by JayRizzo** [comment]
Hi @capitanbarbosa, I hope you are doing well.

Would you create a new issue on this? you can tag this issue in it.  
This is just so we can investigate it further and you can provide more information?  
Tacking on this one might not be seen as the main topic of this has been fixed.

I like to go with one problem per issue raised getting fixed as there is a lot of complications or possible side effects we need to check for.

Have a Great Day!
