### ISSUE TITLE
Can't write "input function" using typewrite()?

### ISSUE THREAD

**Issue by y1027** [asweigart/pyautogui#388]
I want to input password through input function.

x = input('password: ')
pyautogui.typewrite(x)

However, this results to error.

OS: Windows
Python: 3.8

**Comment by vishalramesh** [comment]
This works for me on Windows 10 and Python 3.7.4. Could you elaborate on the error message that you saw?

**Comment by asweigart** [comment]
This seems to work, and unless I can find further information or repro steps, I'm going to close this issue. Thanks for filing it though.
