### ISSUE TITLE
Typo in readme.md file

### ISSUE THREAD

**Issue by sikozonpc** [asweigart/pyautogui#391]
Im not sure if this is known already:

**Issue**:

- In  the Keyboard and Mouse Control > 3rd line `>>> currentMouseX, currentMouseY = pyautogui.position() # Retursn two integes, the x and y of the mouse cursor's current position.`

Small typo in *Retursn*

**Comment by i-need-to-tell-you-something** [comment]
Seems to be fixed in master branch. This can be closed.
