### ISSUE TITLE
it doesn

### ISSUE THREAD

**Issue by StarSkyYe** [asweigart/pyautogui#393]

**Comment by StarSkyYe** [comment]
I want try to use pyautogui for my project. When tested, it doesn't click in the second time. Will you help me?

my test code shows:
----------------------------------------------------------------------------
import pyautogui
import time

for i in range(2):
    indx, indy = pyautogui.locateCenterOnScreen("back.png")
    print(indx, indy)
    pyautogui.leftClick(indx, indy)
    print("done: ", i)
    time.sleep(5)
    indx, indy = pyautogui.locateCenterOnScreen("join_a_meeting.png")
    print(indx, indy)
    pyautogui.leftClick(indx, indy)
    time.sleep(5)

And the output shows:
----------------------------------------------------------------------------
1501 643
done:  0
1573 470
Traceback (most recent call last):
  File "/Users/zzf/Desktop/liyy/hair_v3/testrunner/pyautogui_cli.py", line 6, in <module>
    indx, indy = pyautogui.locateCenterOnScreen("back.png")
TypeError: cannot unpack non-iterable NoneType object

the real result is that it found the image's(join_a_meeting.png) location, but pyautogui.leftClick(indx, indy) doesn't take effect, so it failed when try to found "back.png"

PS: my environment shows:
pyautogui: 0.9.48
python: Python 3.7.4
MacOS: 10.15
javaSDK: 13.0.1

**Comment by i-need-to-tell-you-something** [comment]
Please edit your comment and surround the code with three backticks ``` like this:

\```
for i in range(2):
&nbsp;&nbsp;&nbsp;&nbsp;indx, indy
\```

So that spaces won't be removed. Maybe you need to copy and paste your code again between the backtics. Use the Preview function to see how it will look like. It should look like this:


```
for i in range(2):
  indx, indy
```

Command line results or output should generally also be between triple backticks.
Additionally there is generally the convention to improve the readability by surrounding file paths and filenames with single backticks (write \`pyautogui_cli.py\` get `pyautogui_cli.py`)

**Comment by asweigart** [comment]
I'm going to guess that their problem was that `locateCenterOnScreen()` was unable to find the image and was returning `None`, which isn't unpackable. Closing since this isn't an issue with PyAutoGUI.
