### ISSUE TITLE
screenshot() on ArchLinux in Python 3.6 not overwriting existing file

### ISSUE THREAD

**Issue by MasterChenSensei** [asweigart/pyautogui#395]
If I enter a filename, it takes a screenshot just fine. But if I take another screenshot with the same filename, it doesn't overwrite the existing one, instead it creates a new one with a filename like "Blabla_000.png".

I've read that it uses Scrot on Linux, and that Scrot has "overwrite" disabled as default.
But I've run "Scrot -o" in terminal, which according to its description, would turn "overwriting" on, but it's still not doing so for me.

**Comment by EgZvor** [comment]
The code you're interested in is in https://github.com/asweigart/pyscreeze, there is a function `_screenshot_linux` and it doesn't pass `-o` flag.

**Comment by MasterChenSensei** [comment]
> The code you're interested in is in https://github.com/asweigart/pyscreeze, there is a function `_screenshot_linux` and it doesn't pass `-o` flag.

Thanks a lot, it works now as intended! My mistake was that I was only looking into files from PyAutoGui, which obviously isn't the source to the function in question.
