### ISSUE TITLE
Typewrite ! character with pyautogui

### ISSUE THREAD

**Issue by josephernest** [asweigart/pyautogui#399]
This works to simulate the keystrokes:

    import pyautogui
    pyautogui.typewrite('hello world!', interval=0.1)

except that:

* it writes `hello world§` (with FR keyboard layout)
* it writes `hello world` (with EN keyboard layout)

Is there a workaround?

![](https://gget.it/h3ep/a.gif)

PS: I have a standard Windows 7 x64, Python 3.6, pyautogui 0.9.41 ; I tested with both french keyboard layout and english. I have no other program running (no autohotkey or similar running at the same time).

**Comment by josephernest** [comment]
Duplicate of https://github.com/asweigart/pyautogui/issues/38

**Comment by dezechristophe** [comment]
Hello,
I have the same issue PyAutoGUI 0.9.50
! always give §
any workaround ?
thanks

**Comment by dev-ddoe** [comment]
Hello,

I had similar issue on Linux.
I workaround it using the following at the beginning of the file:

`def isShiftCharacter(character):
	return character.isupper() or character in set('~1234567890°+>?./§%µ')

pyautogui.isShiftCharacter = isShiftCharacter`
