### ISSUE TITLE
Can't select text

### ISSUE THREAD

**Issue by MrSimonC** [asweigart/pyautogui#40]
Hello,
I really hope this is just me, but I can't select text in windows 7, python 3.4 using v0.9.30:

``` python
import pyautogui as p
import time as t

t.sleep(3)
p.keyDown('shift')
p.press('left')
p.keyUp('shift')
```

also:

``` python
p.hotkey('shift', 'left')
```

doesn't work...

The sleep is to give me time to manually click into notepad where I've some text prepared, but am i missing something??

**Comment by xiahongze** [comment]
I am also having this problem. Any idea to get around this?

**Comment by MrSimonC** [comment]
I've completely abandoned using this module since I received no response in eight months from the creator!

**Comment by xiahongze** [comment]
What alternative do you use? I just want to select the text and copy it to a variable.

**Comment by MrSimonC** [comment]
I use this, which combines AutoHotKey and Python:
https://code.google.com/archive/p/pahk

**Comment by dedeswim** [comment]
Hey guys, have you checked whether you have Bloc Num enabled? I had the same issue, but I solved disabling it.

**Comment by MrSimonC** [comment]
Wow. 3 years turn around on your reply. I’ve more than moved on by his point. Good luck though!
*closing issue*

**Comment by KSneijders** [comment]
@dedeswim There are a lot of users with this problem to this day. What do you mean by Bloc num?
