### ISSUE TITLE
Left click 3 times

### ISSUE THREAD

**Issue by learningtour** [asweigart/pyautogui#406]
On macOS Catalina (10.15.3) I created a simple script for operating the calculator.

Using pyautogui.click(1855,506) results in 3 clicks on the same button.
I tried other parameters, but it keeps clicking 3 times. 

Moving to another button on the calculator (even with a short time-out) results in no clicks?

Best regards,
Serge

**Comment by JayRizzo** [comment]
Hi @learningtour I believe I have a fix in my PR #375 if you want the details you can look here: https://github.com/asweigart/pyautogui/issues/369

**Comment by asweigart** [comment]
Fixed by PR #375

**Comment by learningtour** [comment]
Thank you @asweigart !
