### ISSUE TITLE
clipboard

### ISSUE THREAD

**Issue by giancarlocp** [asweigart/pyautogui#41]
management clipboard lack, needed to overcome the problem of type special characters like ® and ™.

**Comment by asweigart** [comment]
This can be done using the pyperclip module. Since this is beyond the scope of pyautogui (there's no keyboard key for  ® and ™) I got to close this. Although I will open a new issue for pyautogui providing an easy way to insert these non-keyboard characters.

**Comment by asweigart** [comment]
Thanks!

**Comment by asweigart** [comment]
Actually, you know what, I'll reopen this. The only way to do this feature (that I can think of) is with pasting clipboard contents.

**Comment by asweigart** [comment]
This works in pyperclip 1.5.26
