### ISSUE TITLE
menu key

### ISSUE THREAD

**Issue by giancarlocp** [asweigart/pyautogui#42]
'menu' key lack.
According to xev:  keycode 135 (keysym 0xff67, Menu)

**Comment by dragon788** [comment]
Good to note. Does this behave different than a right click in some cases?

**Comment by novel-yet-trivial** [comment]
The key name is "f24" in Linux and "apps" in Windows.

**Comment by asweigart** [comment]
This was fixed with the fix for issue 164. Thanks!
