### ISSUE TITLE
Unable to install pyautogui > 0.9.40 from pip with python 2.7

### ISSUE THREAD

**Issue by konserw** [asweigart/pyautogui#426]
Hi,
Unfortunately I still have win7 + python2.7 machine, and recently I tried to install latest pyautogui with pip. Installation failed and it looks like pip tries to install osx packages. I had simmilar issue with keyboard package: https://github.com/boppreh/keyboard/issues/346
In the end I've managed to install pyautogui 0.9.40 (0.9.41 fails). Issue is not reproducible with python 2.7 on windows 10 machine, so it is not old python's fault, and probably not pip itself. 
Please can you check if there is something with your setup.py? Or maybe it's setuptools problem?

**Comment by vosslab** [comment]
Confirm problem on macOS 10.13.6 and 10.15.5, workaround:

`pip install pyautogui==0.9.40`

**Comment by asweigart** [comment]
This has been fixed since we've backed out the rubicon edits.
