### ISSUE TITLE
"Module not found error"

### ISSUE THREAD

**Issue by homelyseven250** [asweigart/pyautogui#429]
After installing with the following command `pip3 install pyautogui`, I have found the following error when trying to import it:
```bash
homelyseven250@my-pc:~/Documents/Python Tests$ python3 test1.py 
Traceback (most recent call last):
  File "test1.py", line 1, in <module>
    import pyautogui 
ModuleNotFoundError: No module named 'pyautogui'
```
Is this an error with Python or my Ubuntu 18.04 machine or with pyautogui?
Any help would be appreciated.

**Comment by theshinyknight** [comment]
Open terminal and type `python3`.
Once you have the python prompt, type `import pyautogui`

If that give you an error, try to check that your PYTHONPATH env variable is set correctly.

**Comment by homelyseven250** [comment]
That worked perfectly, but now I realize what caused it, and I don't know how to fix it. I installed python 3.8, as well as the built-in 3.6 as I thought that was how you got pip on ubuntu. I am now facing the issue of: `pip3` installs packages to python 3.6, but typing `python3` runs python 3.8. I can't find any solutions online, but have found that running `python3.6` does run 3.6.
![screenshot](https://user-images.githubusercontent.com/61860079/81650920-3a8bd000-942a-11ea-9ace-e80de5acebef.png)

**Comment by cab-1729** [comment]
I would recommend uninstalling python 3.8, it is new and lacks the support for many modules , I consistently use 3.7.2 and have absolutely no problems with it . If you want to keep python 3.8 but use 3.6 as the interpreter in the command line , edit the path to exclude python 3.8 and put in python 3.6 ,
