### ISSUE TITLE
Mouse functions like click or move not working for Python 3.8.x

### ISSUE THREAD

**Issue by code-lucidal58** [asweigart/pyautogui#438]
The functions do not throw any exception. However, `import pyautogui` shows a warning, `/usr/local/lib/python3.8/site-packages/rubicon/objc/ctypes_patch.py:21: UserWarning: rubicon.objc.ctypes_patch has only been tested with Python 3.4 through 3.7. You are using Python 3.8.2. Most likely things will work properly, but you may experience crashes if Python's internals have changed significantly.`

**Comment by kiagam** [comment]
I've been using here normally on 3.8. Maybe reinstall the library?

**Comment by code-lucidal58** [comment]
This issue still exists
```
Python 3.8.5 (default, Jul 21 2020, 10:48:26)
[Clang 11.0.3 (clang-1103.0.32.62)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyautogui
/usr/local/lib/python3.8/site-packages/rubicon/objc/ctypes_patch.py:21: UserWarning: rubicon.objc.ctypes_patch has only been tested with Python 3.4 through 3.7. You are using Python 3.8.5. Most likely things will work properly, but you may experience crashes if Python's internals have changed significantly.
  warnings.warn(
```
pyautogui version: 0.9.50

**Comment by Steve3029** [comment]
I have the same issue. It seems like that this issue occurs on mac.
`Python 3.8.6 (default, Oct 24 2020, 18:08:48)
[Clang 12.0.0 (clang-1200.0.32.21)] on darwin`

**Comment by toprakfirat** [comment]
I have the same problem

**Comment by bukakkkkl** [comment]
i have same problem

**Comment by bukakkkkl** [comment]
please help

**Comment by code-lucidal58** [comment]
Closing this issue is not being addressed.
