### ISSUE TITLE
New folder Issue

### ISSUE THREAD

**Issue by VedantBhalgama** [asweigart/pyautogui#448]
Hello!

This is my code. My problem is that first time if i create a directory called "Images" It takes the screenshot. But if i execute the script next time again. It is going to give me a error like this

WindowsError: [Error 183] Cannot create a file when that file already exists. 

And I want that even after the folder "Images" exeist i want to save all screenshots to that folder only. Please help me!

```
import pyautogui, os
os.mkdir("C:\Images")
myScreenshot = pyautogui.screenshot()
myScreenshot.save(r'C:\Images\Image.jpg)
```

**Comment by Rayquaza13** [comment]
**Check if the folder exists. If it doesn't exist, create it.**
```
import pyautogui, os
if not os.path.exists("C:\Images"):
    os.makedirs("C:\Images")
myScreenshot = pyautogui.screenshot()
myScreenshot.save(r'C:\Images\Image.jpg)
```

**Comment by asweigart** [comment]
Thanks for bringing this up. This is a part of Pillow, not PyAutoGUI, so I can't change this.
