### ISSUE TITLE
"Special Notes About Ubuntu" in the docs don't seem to apply anymore

### ISSUE THREAD

**Issue by freebiesoft** [asweigart/pyautogui#450]
this section in the docs: https://pyautogui.readthedocs.io/en/latest/screenshot.html#special-notes-about-ubuntu, doesn't seem to apply for me on Ubuntu 18.04.

I have had no issues with using pyautogui so far.

I suspect these notes are outdated.

**Comment by asweigart** [comment]
Thanks! I'll pull it out.
