### ISSUE TITLE
Some characters are not working with German layout keyboard

### ISSUE THREAD

**Issue by E2w4UmWh** [asweigart/pyautogui#46]
I do have a strange problem, using a German keyboard layout. 

> > > pyautogui.typewrite("!\"#$%&()_+H")  
> > > !"'$%&()_*H

Which means '#' results in an ' and '+' results in an *.
This is quite strange, as all other characters seem to work.

The software, I'm targeting to, is very dumb. It does not accept 'CTRL'+'V' nor 'ALT'+'35' in it's text fields, so I really have to simmulate single keystrokes. Unfortunately I do need the Hash # sign to trigger some actions.

OS: Windows 8; Python: V3.4.3

Are there any ideas for a work around? Anny suggestions appreciated!

**Comment by E2w4UmWh** [comment]
I had time to dig a bit deeper into that problem and found the following: The characters wrongly showing up are always the one, showing up when shift is pressed wrongly (on a real keyboard):
#:' , +:* , <:>

Putting the characters into 'keyboardMapping' first, did not have any effect.  As a successfull workaround, then I patched the following code in _pyautogui_win.py:

def _keyDown(key):
    if key not in keyboardMapping or keyboardMapping[key] is None:  return
    needsShift = pyautogui.isShiftCharacter(key)
### insert this code, exactly here:
    if key == '#': needsShift = False
    if key == '+': needsShift = False
    if key == '<': needsShift = False
    #print(key,needsShift) #####debug
### continue

This has SOLVED my problem with some special characters and hopefully may help others, with non-US keyboards.

By the way: Deleting #,+,< in the following function, did NOT work (util.py  in .\pyautogui):
def isShiftCharacter(character):
   return character.isupper() or character in '~!@#$%^&*()_+{}|:"<>?'

Maybe .isupper() regards these characters as upper? I didn't check further

**Comment by Tattoo** [comment]
It would be great if pyautogui would support other keyboard layouts than English. I'm willing to help with implementing the Finnish layout

**Comment by Semmu** [comment]
Same problem here using Hungarian layout, # results in +, and + results in (. Other anomalies may exists too, I didn't test every key.

I'm willing to help in the Hungarian mapping. (or find a keyboard-layout independent solution? don't know if there is any)

**Comment by georgemunteanu** [comment]
hello guys. on german keyboard, I faced this problem. Character "\" is converted into character "?" . I tried the suggestion mentioned above  ( that is altering: pyautogui_win.py > def_keyDown ), but "\"  is still converted into "?".. Therefore please share a hint on this.

**Comment by i-need-to-tell-you-something** [comment]
In my case a similar problem seems to be connected to what these (Estonian) keys are on a US keyboard. E.g. these: `"test !\"#¤%&/()=?`PÜÕ*LÖÄ;:_ 1234567890+´püõ'löä,.- " `get typewrited as these: `test !@#%^7()0_=P|L,>? 1234567890_p\l,./ `

**Comment by i-need-to-tell-you-something** [comment]
So i dug deeper and learned that the problem underlying my issue had a workaround (execute `setxkbmap` after every boot) mentioned [here](https://code.google.com/archive/p/semicomplete/issues/55). Newer bug reports are [here ](https://github.com/jordansissel/xdotool/issues)for that similar tool having the same issues.

**Comment by margilc** [comment]
I had the same problem as georgemunteanu, and found a workaround which should be applicable to all non-english keyboard problems with autogui on windows. For further information look here:
http://stackoverflow.com/questions/36040370/encoding-of-backslash-in-pythons-pyautogui/36055972#36055972

**Comment by asweigart** [comment]
Folding this into issue #137
