### ISSUE TITLE
click() not working on Mac Os

### ISSUE THREAD

**Issue by eddjimlab** [asweigart/pyautogui#467]
None of clicks work on Mac Os
I tried pyautogui.doubleClick(x,y, interval=0.25)
and pyautogui.click(x, y, clicks=2, interval=0.25)
try sudo as well

Get only mouse move to position

**Comment by eddjimlab** [comment]
This works fine for me.
You have to install another library pynput

from pynput.mouse import Listener, Controller, Button

mouse = Controller()

pyautogui.moveTo(x, y)
mouse.click(Button.left, 2)

**Comment by asweigart** [comment]
The 0.9.51 version includes several mouse-related macOS fixes, so I'm going to close this. Please re-open if your problems still persist. Thanks!
