### ISSUE TITLE
AttributeError: 'int' object has no attribute 'sleep'

### ISSUE THREAD

**Issue by DrPlanecraft** [asweigart/pyautogui#468]
Hello, I would like to ask why I would have this error,

my python version:
Python 3.7.7 (default, May  6 2020, 11:45:54) [MSC v.1916 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 7.16.1 -- An enhanced Interactive Python.

My code (all the code after the error have been commented):
import time
import pyautogui
print ('Start')
pyautogui.FAILSAFE=True
pyautogui.time=1
print('1')
time.sleep(2)
mousePos = pyautogui.position()
print('2')
pyautogui.click(mousePos, interval=0)
# print('3')
# while True:
#     print('4.1')
#     pyautogui.press(['/'])
#     print('4.2')
#     pyautogui.typewrite('Hello World, THIS IS A AUTOMATIC PYTHON LOOP!\n', interval=0.25)
#     print("DONE!!")

I hope you can help in this issue
full error message:

runfile('C:/Macro/temp.py', wdir='C:/Macro')
Start
1
2
Traceback (most recent call last):

  File "C:\Macro\temp.py", line 10, in <module>
    pyautogui.click(mousePos, interval=0)

  File "C:\ProgramData\Anaconda3\envs\AI\lib\site-packages\pyautogui\__init__.py", line 588, in wrapper
    returnVal = wrappedFunction(*args, **kwargs)

  File "C:\ProgramData\Anaconda3\envs\AI\lib\site-packages\pyautogui\__init__.py", line 985, in click
    time.sleep(interval)

AttributeError: 'int' object has no attribute 'sleep'

**Comment by asweigart** [comment]
You set pyautogui.time to an integer value, which caused this problem. I think what you wanted to do was set pyautogui.PAUSE.
