### ISSUE TITLE
Non Type Error

### ISSUE THREAD

**Issue by Kingfrankbob** [asweigart/pyautogui#471]
When i Try to call the pyautogui.click('Example Image.png') in a function or loop i get this error:  File "/home/pi/Documents/Auto.py", line 19, in restart_bruh
    pyautogui.click('ssjn.png')
  File "/home/pi/.local/lib/python3.7/site-packages/pyautogui/__init__.py", line 588, in wrapper
    returnVal = wrappedFunction(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/pyautogui/__init__.py", line 970, in click
    x, y = _normalizeXYArgs(x, y)
TypeError: cannot unpack non-iterable NoneType object

Heres my code: (sorry a bit messyy)
``

import pyautogui
import random
import time
import os
x = 0
time.sleep(2)
y = pyautogui.locateCenterOnScreen('jjn.png')
z = pyautogui.locateCenterOnScreen('cjjn.png')
#a, b = y
#pyautogui.moveTo(a, b, 2)

def restart_bruh():
  pyautogui.press('f5')         
  time.sleep(10)
  pyautogui.size()
  (848, 480)
 # pyautogui.click('jjn.png')
  #pyautogui.click('cjjn.png')
  pyautogui.click('ssjn.png')
  #pyautogui.moveTo(340, 310, 1)
  #pyautogui.click()
  #pyautogui.moveTo(330, 310, 1)
  #pyautogui.click()
  #pyautogui.moveTo(320, 310, 1)
  #pyautogui.click()
  #pyautogui.moveTo(310, 310, 1)
  #pyautogui.click()
  #pyautogui.moveTo(300, 310, 1)
 # pyautogui.click()
  #pyautogui.moveTo(295, 310, 1)
  #pyautogui.click()
  #pyautogui.moveTo(285, 310, 1)
  #pyautogui.click()
  #pyautogui.moveTo(275, 310, 1)
 #pyautogui.click()
  #pyautogui.moveTo(265, 310, 1)
  #pyautogui.click()
  #pyautogui.moveTo(255, 310, 1)
  #pyautogui.click()
  #pyautogui.moveTo(245, 310, 1)
 # pyautogui.click()
 # pyautogui.moveTo(235, 310, 1)
  #pyautogui.click()
 

time.sleep(5)
print(y)  
for i in range(9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999):
 if x == 10:
   time.sleep(1)
   print("restarting")
   restart_bruh()
#   pyautogui.click('ssjn.png')
   x = 0
   print("restart done")
 else:    

     print("Loop")
     pyautogui.keyDown(" ")
     time.sleep(0.5)
     pyautogui.keyUp(" ")
     time.sleep(0.5)          
     x = x+1
     print(x)
``
Please help I have no idea whats wrong!
(also no idea how to use code function sorry!)

``

**Comment by milkpirate** [comment]
Same problem:
```
>>> import pyautogui
>>> pyautogui.click('images/settings.png')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/.cache/pypoetry/virtualenvs/dsa-characters-uY1pLEV0-py3.10/lib/python3.10/site-packages/pyautogui/__init__.py", line 598, in wrapper
    returnVal = wrappedFunction(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/dsa-characters-uY1pLEV0-py3.10/lib/python3.10/site-packages/pyautogui/__init__.py", line 980, in click
    x, y = _normalizeXYArgs(x, y)
TypeError: cannot unpack non-iterable NoneType object
>>>
```
Any solution?

**Comment by Kingfrankbob** [comment]
Not so far :(

**Comment by milkpirate** [comment]
@Kingfrankbob try installing OpenCV, https://pypi.org/project/opencv-python/. `.click()` hands it internally to OpenCV if it is receives and image path. If is not installed, some internal fucntion retruns `None`. Other dependencies I had to install for my project were:

```
$ cat pyproject.toml
...
[tool.poetry.dependencies]
PyAutoGUI = "^0.9.53"
Pillow = "^9.0.1"
opencv-python = "^4.5.5"
...
```

Not sure if `Pillow` is necessary, I guess I needed it for screenshots. BTW versions were chosen by [poetry](https://python-poetry.org/docs/), use your prefered package installer without explicitly stating them will suffice I guess.

**Comment by Kingfrankbob** [comment]
Sweet! It works, thanks!!!!!
