### ISSUE TITLE
Ctrl+Alt+Delete Command not working

### ISSUE THREAD

**Issue by Ali-Hassan785** [asweigart/pyautogui#478]
I am not sure why, but pyautogui.hotkey('ctrl','alt', 'delete') doesn't work!

I tried these and they work well:
pyautogui.hotkey('alt', 'f4')
pyautogui.hotkey('ctrl', 'shift', 'esc')
But pyautogui.hotkey('ctrl','alt', 'delete')  doesn't work as well. 
But I had no success.

**Comment by asweigart** [comment]
The Windows operating system doesn't let applications simulate pressing Ctrl+Alt+Del, so this is something that PyAutoGUI will never be able to do.
