### ISSUE TITLE
locateAll() assumes that image file name is str

### ISSUE THREAD

**Issue by Tattoo** [asweigart/pyautogui#48]
Hi,

`locateAll()` assumes that `needleImage` is a Python's `str`. It can however also be `unicode` which is valid string for `open()`.

At least you should properly check and report the exception. Right now, `needleImage` stays as unicode string which results in very cryptic error messages.

**Comment by asweigart** [comment]
This has been fixed in PyScreeze 0.1.26. Thanks for pointing this out!

https://github.com/asweigart/pyscreeze/commit/8992da81aac7019d28bdc0a2f9de9d0d4afa6bff
