### ISSUE TITLE
I download it but I can't use it 

### ISSUE THREAD

**Issue by gokhangezgin** [asweigart/pyautogui#487]
Hello I use cmd and pip. I download pyautogui but when I try to import in Pycharm it doesn't find anything. Can you help me

**Comment by jorg-j** [comment]
Pycharm sets up a venv for each project. You need to install it within the venv.

**Comment by nimit2801** [comment]
@gokhangezgin if the problem is solved please close the issue :) if you need any further assistance please the community will be more than happy to answer you. :)
