### ISSUE TITLE
Is it possible to save a file in current working directory?

### ISSUE THREAD

**Issue by mulaixi** [asweigart/pyautogui#488]
I'm trying to save a webpage with _ctrl+s_. But I can't set the directory for saving when the save file window appears.  The examples I could find about it are to save screenshots in a specified directory. But I'm not sure how to use it in my case, and I'd like to save exactly in the current working directory. Is there a way to set it as current working directory?
OS: Win10
Python: 3.8.6
pyautogui: 0.9.52

```
page = webdriver.Chrome(executable_path='chromedriver.exe')
page = page.get(url)
pyautogui.hotkey('ctrl', 's')
time.sleep(3)
pyautogui.typewrite('foo' + '.html')
pyautogui.press('enter')
```

Edit: for now, I solved the issue by moving the files after downloading, but I'd like to know if there is a way to do set the path before saving the file.

**Comment by tandal** [comment]
@mulaixi 
When the **Save As** window opens the filename is highlighted. If you include the directory you want to save to in the filename, that should work. Hopefully this helps out.

**Example**
pyautogui.typewrite('C:\Users\username\directory\example.htm')
