### ISSUE TITLE
Tweening not working as expected (win 7, Python)

### ISSUE THREAD

**Issue by bleuetnoir** [asweigart/pyautogui#5]
Hello,

Tween was not working for me and found that the value tween function was receiving was not within the 0..1 range.

I have not looked further for the why and quickly modified the code to this:

```
if duration <= MINIMUM_DURATION:
    print("duration check")   
    if moveOrDrag == 'move':
        print("move") 
        platformModule._moveTo(x, y)
    else:
        print("drag") 
        platformModule._dragTo(x, y, button)
    return

tweenfinished = False
starttime = time.time()

while(tweenfinished == False):
    _failSafeCheck()
    elapsedtime = time.time() - starttime

    tweenvalue = min(1, max(0, float(elapsedtime) / float(duration)))

    pointOnLine = tween(tweenvalue) # range 0 / 1
    tweenX, tweenY = getPointOnLine(startx, starty, x, y, pointOnLine)
    tweenX, tweenY = int(tweenX), int(tweenY)

    if moveOrDrag == 'move':
        platformModule._moveTo(tweenX, tweenY)
    else:
        # only OS X needs the drag event specifically
        platformModule._dragTo(tweenX, tweenY, button)
    if (elapsedtime < duration) :
        time.sleep(0.001)
    else :
        tweenfinished = True

# TODO: Test range. Should not be necessary with previous change??        
# Ensure that no matter what the tween function returns, the mouse ends up
# at the final destination.
#if moveOrDrag == 'move':
#    platformModule._moveTo(x, y)
#else:
#    platformModule._dragTo(x, y, button)
```

  This would probably require a second look and more test before such fix could be submited as a pull request but it's working well for what I need (and I'm a little bit pressured by time).

  Thanks for the great library!

Eric

**Comment by neatville** [comment]
I use Ubuntu also, and I get an error when I try it (whether it's python2 or 3). 
     pyautogui.moveTo(100, 100, 2, pyautogui.tweens.easeInQuad)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    AttributeError: 'module' object has no attribute 'tweens'

**Comment by adamkdean** [comment]
I am also getting this issue, and it's 2016 now. 

Traceback (most recent call last):
  File "c:\Users\Adam\Projects\OTP\test.py", line 8, in <module>
    pyautogui.moveTo(500, 500, duration=2, tween=pyautogui.tweens.easeInOutQuad) 
AttributeError: module 'pyautogui' has no attribute 'tweens'

**Comment by asweigart** [comment]
The update to the documentation in 166b8283192840a2b650edf05f41cf56f7396cfd corrects this. The `tweens` module no longer exists, instead you just specify the function directly: `pyautogui.easeInOutQuad` instead of `pyautogui.tweens.easeInOutQuad`.

**Comment by kimborgen** [comment]
@asweigart Why is this still not fixed in the readme? :thinking:
