### ISSUE TITLE
Import error when another file is named copy.py in the same folder

### ISSUE THREAD

**Issue by Fornost461** [asweigart/pyautogui#505]
### Steps to reproduce:
1. Create a file **first.py** with the following content.
```
import pyautogui
print('Message from first.py.\n')
```
2. In the same folder, create a file **copy.py** with the following content.
`print('Message from copy.py.\n')`

3. In a terminal, from this folder, run `python first.py`.

### Resulting output
```
Message from copy.py.

Traceback (most recent call last):
  File "first.py", line 1, in <module>
    import pyautogui
  File "/usr/lib/python3.8/site-packages/pyautogui/__init__.py", line 183, in <module>
    import pyscreeze
  File "/usr/lib/python3.8/site-packages/pyscreeze/__init__.py", line 25, in <module>
    from PIL import Image
  File "/usr/lib/python3.8/site-packages/PIL/Image.py", line 38, in <module>
    import xml.etree.ElementTree
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 2053, in <module>
    from _elementtree import *
AttributeError: module 'copy' has no attribute 'deepcopy'
```
### Remark

Notice that the second instruction from file `first.py` was apparently not executed.
I used to not have this problem on another Linux distro that I used about a year or so ago.

### My specs
OS: Manjaro Linux
Python 3.8.6
Installed package python-pyautogui 0.9.52-4 from [Arch User Repository](https://aur.archlinux.org/packages/python-pyautogui) (last update there: 2020-12-03 23:27).

**Comment by dplefevre** [comment]
The problem is that copy is a built-in module which offers the deepcopy function. By having a local file called 'copy.py', you import that instead, and when another imported line of code goes looking for the 'deepcopy' method, it doesn't find it, and throws an error. Rename copy.py to something else and the error goes away.

**Comment by Fornost461** [comment]
Ok thank you I didn't know.
