### ISSUE TITLE
Choose an item in a Listbox

### ISSUE THREAD

**Issue by josephernest** [asweigart/pyautogui#520]
Thank you @asweigart for making this project!

I have a dialog box with a `ListBox`:

![](https://docs.microsoft.com/en-us/windows/win32/controls/images/lb-roster.png)

I need to choose one specific element in this list, by text. Example: `item = 'Kohl, Franz'`

I can't do a screenshot of this text in advance, because this text could be anything, dynamically. I imagine [Screenshot functions](https://pyautogui.readthedocs.io/en/latest/screenshot.html) won't help here?

Or maybe we *could* render the text with the default Windows GUI font (Segoe UI?) to a .png, and then use Screenshot functions?

Is there a way to do this?

**Comment by asweigart** [comment]
You might want to use pytesseract to do OCR to find where the text is, but this is beyond the scope of pyautogui. I wrote a blog post on pytesseract here (though it's only a basic tutorial and doesn't tell you how to locate the text within an image): https://inventwithpython.com/blog/2021/01/11/text-recognition-in-python-with-pytesseract/
