### ISSUE TITLE
Import and installation are correct, but compilation is wrong

### ISSUE THREAD

**Issue by FWJerome** [asweigart/pyautogui#528]
<img width="1440" alt="WX20210111-225926@2x" src="https://user-images.githubusercontent.com/12042541/104198033-b4b0a080-5460-11eb-8298-ced51217d9cf.png">

**Comment by asweigart** [comment]
An older version of PyAutoGUI for macOS used rubicon, but we had some problems with it so I switched back to pyobjc. The solution is to update your version of PyAutoGUI.
