### ISSUE TITLE
Make PyAutoGUI work on headless AWS.

### ISSUE THREAD

**Issue by chrism91** [asweigart/pyautogui#54]
Hi!

Love this module. I am working on developing some pieces that are running on instances in the AWS cloud EC2 servers. I would like to use some of the autogui features as a web-console workaround. But I get Xlib errors. Is there any workaround for them? faking a VGA output? I am able to get a desktop via VNC.

Thanks!

**Comment by asweigart** [comment]
I'm no xlib expert, I cobbled those functions together mostly from StackOverflow answers. But if there's a solution for this, I'd love to get pull requests.

But for me personally anyway, this isn't on my road map of things to do. You might have better luck with something like Selenium.

**Comment by chrism91** [comment]
Just got it to work! Sorry for the invalid request. Side note: Is there a way to pass variables copied using keyboard shortcuts? I have 'ctrl' 'c' copied a line of text, and would like to know if your module has any knowledge of the content performed by shortcuts.

Thanks!
Chris

**Comment by chrism91** [comment]
Selenium is dope. But for the kinds of authentication I'm working around, this tool is ideal.

**Comment by duedl0r** [comment]
Could you describe how you got it to work?
Cheers

**Comment by dragon788** [comment]
Has anyone tested this with `Xvfb` or it's successor (can't recall the name offhand)? They implement a passable X server that can be utilized by exporting `DISPLAY=:99` or something similar and running Xvfb with the appropriate arguments.

**Comment by asweigart** [comment]
Currently PyAutoGUI doesn't support remote/headless machines. I've created a master issue #133 to track the development of this feature.
