### ISSUE TITLE
Windows KeyError: 'DISPLAY'

### ISSUE THREAD

**Issue by medoix** [asweigart/pyautogui#549]
I am following the documentation to install `pyautogui` on Windows.

Installed via
```
pip3 install pyautogui
```

Test file
```
import pyautogui
pyautogui.position()
```

Result
```
python3 test.py       
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import pyautogui
  File "/home/medoix/.local/lib/python3.8/site-packages/pyautogui/__init__.py", line 241, in <module>
    import mouseinfo
  File "/home/medoix/.local/lib/python3.8/site-packages/mouseinfo/__init__.py", line 223, in <module>
    _display = Display(os.environ['DISPLAY'])
  File "/usr/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'DISPLAY'
```

Am i meant to define the display somehow in Windows? I gather this is auto provided in Linux

**Comment by medoix** [comment]
Fixed: VSCode was opening up a WSL shell instead of Powershell.

**Comment by mlr07** [comment]
Just to clarify... `pyautogui` will not work with `WSL`? Based on what I have read elsewhere this has to do with the lack of an X-server in the linux subsystem. Similar to how `pyautogui` will not work over a remote or headless terminal session.

**Comment by medoix** [comment]
> Just to clarify... `pyautogui` will not work with `WSL`? Based on what I have read elsewhere this has to do with the lack of an X-server in the linux subsystem. Similar to how `pyautogui` will not work over a remote or headless terminal session.

correct, there is no x server or GUI to control.
