### ISSUE TITLE
Chinese Documentation is 404 

### ISSUE THREAD

**Issue by gongjiaji** [asweigart/pyautogui#555]
The link of Chinese documentation is no longer available. Please consider fixing the link.

**Comment by gongjiaji** [comment]
Find Chinese documentation in the repo below:

NYcleaner/muxuezi.github.io/posts/doc-pyautogui.ipynb

**Comment by asweigart** [comment]
Thanks for pointing this out. I've copied the documentation to this repo so it won't get lost again.
