### ISSUE TITLE
Can you provide Function Description please ?!

### ISSUE THREAD

**Issue by dschiller** [asweigart/pyautogui#565]
It's nice to have the Documentation at https://pyautogui.readthedocs.io. But having a full Function Description is much better. For example here ( https://pyautogui.readthedocs.io/en/latest/mouse.html ) you describe just two of the Drag Methods. Would be amazing to see the internal python Help ( `help(pyautogui` ) somewhere on https://pyautogui.readthedocs.io like https://github.com/asweigart/pyautogui/blob/master/pyautogui/__init__.py.

**Comment by asweigart** [comment]
Yes, the documentation will eventually be brought up to date. Sorry for the delay on this.

**Comment by dschiller** [comment]
Hi Al, no problems. Thanks for investigation.
