### ISSUE TITLE
How to make it faster ?

### ISSUE THREAD

**Issue by Nababuku** [asweigart/pyautogui#568]
Hi, need to find mouse cords, but this here is so to slow:

import pyautogui, sys
print('Press Ctrl-C to quit.')
try:
    while True:
        x, y = pyautogui.position()
        positionStr = 'X: ' + str(x).rjust(4) + ' Y: ' + str(y).rjust(4)
        print(positionStr, end='')
        print('\b' * len(positionStr), end='', flush=True)
except KeyboardInterrupt:
    print('\n')

**Comment by HuangPatrick16777216** [comment]
Set the pause to 0:

```
import pyautogui
pyautogui.PAUSE = 0
```
It is default 0.1, which means it can perform a max of 10 actions per second.
Setting it to 0 will make it much faster.
