### ISSUE TITLE
What is 'left' and 'top' in '(left, top, width, height)'?

### ISSUE THREAD

**Issue by BlazerYoo** [asweigart/pyautogui#569]
When using the `locateOnScreen` function, what exactly are `left` and `top` (the first two values in the tuple that is returned?

![image](https://user-images.githubusercontent.com/69565038/118243320-4f030e00-b46c-11eb-8ff5-58d2ab0df464.png)

**Comment by MAX-EINSTEIN** [comment]
locateOnScreen returns a 4-integer tuple: (left, top, width, height).

(left, top)                     (right, top)  
          _________________
          |                        |
          |________________|
(left, bottom)              (right, bottom)
