### ISSUE TITLE
The have to make a new layout everytime is straight up stupid

### ISSUE THREAD

**Issue by LiamIsAGod666** [asweigart/pyautogui#573]
Is the error a mistake? If so then please try your best to fix it. Though the error message makes it seem like the error was intended, and if it is then that was a pretty bloody stupid idea. Sometimes I don't want to start with a goddamn "clean" unused layout.

**Comment by jorg-j** [comment]
Can you be more specific?
What error are you seeing? What actions are you performing to result in this error?

**Comment by LiamIsAGod666** [comment]
never mind I was pissed. My bad.
