### ISSUE TITLE
pyautogui.pixel() intermittent error: windll.user32.ReleaseDC failed : return 0

### ISSUE THREAD

**Issue by jwhendy** [asweigart/pyautogui#579]
I sporadically get the following error when trying to use `pyautogui.pixel()` on Windows 10. Here's on a fresh command line interface. It failed the second time, but ran easily 10 in a row after and did not fail.

```
Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyautogui
>>> pyautogui.pixel(0, 0)
(240, 240, 240)
>>> pyautogui.pixel(0, 0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\a1rwhzz\AppData\Roaming\Python\Python39\site-packages\pyscreeze\__init__.py", line 613, in pixel
    return (r, g, b)
  File "C:\Users\a1rwhzz\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 124, in __exit__
    next(self.gen)
  File "C:\Users\a1rwhzz\AppData\Roaming\Python\Python39\site-packages\pyscreeze\__init__.py", line 122, in __win32_openDC
    raise WindowsError("windll.user32.ReleaseDC failed : return 0")
OSError: windll.user32.ReleaseDC failed : return 0
>>> pyautogui.pixel(0, 0)
(240, 240, 240)
>>> pyautogui.pixel(0, 0)
(240, 240, 240)
>>> pyautogui.pixel(0, 0)
...
```

I'm unable to reliably reproduce it, though it seems that many others have gotten the error (and sometimes related to other functions, not just `pixel()`). Sadly, many of the suggestions just say to download to 3.7. I'm surprised it's not coming up more here; he closest I could find was #229 which is about some type of limit, which doesn't seem to be the cause here.
- [i got a windows error and os error while making a pyautogui program](https://stackoverflow.com/questions/62359699/i-got-a-windows-error-and-os-error-while-making-a-pyautogui-program)
- [Python windll.user32.ReleaseDC failed error](https://stackoverflow.com/questions/64700237/python-windll-user32-releasedc-failed-error)
- [“windll.user32.ReleaseDC failed : return 0” from pyautogui.pixel](https://stackoverflow.com/questions/64741292/windll-user32-releasedc-failed-return-0-from-pyautogui-pixel)
- [Python PyAutoGui pixelMatchesColor raises windll.user32.ReleaseDC Error](https://stackoverflow.com/questions/62708880/python-pyautogui-pixelmatchescolor-raises-windll-user32-releasedc-error)
- [Pyautogui and pyscreeze crash with windll.user32.ReleaseDC failed](https://stackoverflow.com/questions/59146513/pyautogui-and-pyscreeze-crash-with-windll-user32-releasedc-failed)
- [raise WindowsError("windll.user32.ReleaseDC failed : return 0") OSError: windll.user32.ReleaseDC failed : return 0 error in python](https://www.reddit.com/r/pythonhelp/comments/idwggk/raise_windowserrorwindlluser32releasedc_failed/)
- [windll.user32.ReleaseDC failed](https://www.reddit.com/r/learnpython/comments/ejm0f9/windlluser32releasedc_failed/)
- [OSError: windll.user32.ReleaseDC failed : return 0](https://www.reddit.com/r/learnpython/comments/lcb9ix/oserror_windlluser32releasedc_failed_return_0/)
- [pyautogui.pixel and pyautogui.mouseInfo giving me an error](https://www.reddit.com/r/learnpython/comments/lp4v53/pyautoguipixel_and_pyautoguimouseinfo_giving_me/)

In my actual environment (a jupyter notebook) it seems to fail more often, but is unpredictable. Just re-running the cell often works the next time.

Is there a way to better track this down? Obviously if one is automating something, an unpredictable error that breaks flow is a pretty huge hurdle! Happy to provide more information or try any suggestions in order to assist.

Edit: fixed link issues

**Comment by jwhendy** [comment]
I'm not sure if this is a helpful finding, but I did a sort of DOE on the potential methods for obtaining a screenshot and finding out the pixel color. The interaction between these two functions is one way to reproduce the error in `releaseDC`. I tested combinations of the following:

- screenshot: locally reproduced `pyautogui.screenshot()`, `pywin32` based, `PIL.ImageGrab.grab()`, and `pyautogui.screenshot()`
- pixel color: locally reproduced `pyautogui.pixel()`, `im.getpixel()` (PIL), `pyautogui.pixel()`

Results, where `pass` is 100% passing, `fail` is 100% failure, and `inter` is irregular failures.

```
| screenshot             | pixel                | result |
|------------------------+----------------------+--------|
| local screenshot()     | local pixel()        | inter  |
| win32py                | local pixel()        | fail   |
| PIL.ImageGrab.grab()   | local pixel()        | inter  |
| pyautogui.screenshot() | local pixel()        | faill  |
|------------------------+----------------------+--------|
| local screenshot()     | PIL.Image.getpixel() | pass   |
| win32py                | PIL.Image.getpixel() | pass   |
| pyautogui.screenshot() | PIL.Image.getpixel() | pass   |
| PIL.ImageGrab.grab()   | PIL.Image.getpixel() | pass   |
|------------------------+----------------------+--------|
| local screenshot()     | pyautogui.pixel()    | inter  |
| win32py                | pyautogui.pixel()    | pass   |
| pyautogui.screenshot() | pyautogui.pixel()    | inter  |
| PIL.ImageGrab.grab()   | pyautogui.pixel()    | inter  |
```

I did some timings which might be of interest.

```
### testing times for 1000 screenshots
import time

t0 = time.time()
for i in range(1000):
    _ = _screenshot_win32_2()
print('pywin32 screenshot: ', time.time()-t0)

t0 = time.time()
for i in range(1000):
    _ = gui.screenshot()
print('pyautogui.screenshot: ', time.time()-t0)

t0 = time.time()
for i in range(1000):
    _ = ImageGrab.grab()
print('PIL: ', time.time()-t0)

# pywin32 screenshot:  34.074795961380005
# pyautogui.screenshot:  34.17940545082092
# PIL:  33.86239743232727

### comparing pyautogui.pixel() vs. using PIL to obtain it from a screenshot
t0 = time.time()
for i in range(1000):
    _ = gui.pixel(0, 0)
print('pyautogui.pixel(): ', time.time()-t0)

t0 = time.time()
for i in range(1000):
    im = gui.screenshot()
    _ = im.getpixel((0, 0))
print('pyautogui.screenshot() + im.getpixel(): ', time.time()-t0)

#pyautogui.pixel():  16.653464794158936
#pyautogui.screenshot() + im.getpixel():  33.78006649017334
```

So, even though `im.getpixel()` works with any screenshot method, it's pretty slow to get it from an image (after taking it) vs. how `pyautogui.pixel()` currently does it. 

I think the key finding is that the `pywin32` based screenshot method (like [this](https://www.programmersought.com/article/49766989757/) and [this](https://stackoverflow.com/questions/3586046/fastest-way-to-take-a-screenshot-with-python-on-windows/3586280#3586280)) is compatible with `pyautogui.pixel()`, whereas `PIL.ImageGrab.grab()` is not (and both are using `pywin32` stuff).

Here's [the jupyter notebook](https://gist.github.com/jwhendy/88745aecb87467a2e5db73be4dfa206d) I was working from.

**Comment by jwhendy** [comment]
Greetings,

See [this finding](https://github.com/python-pillow/Pillow/issues/5536#issuecomment-860108785) at an issue I opened with `pillow` to ask there about the observed interaction between `pyautogui.pixel()` and `PIL.ImageGrab.grab()`. They've helped narrow this down to an inability of `ctypes.windll` to deal with the negative handles sometimes returned from `GetDC()`, which is what's causing this error with `ReleaseDC()`.

[PR 73](https://github.com/asweigart/pyscreeze/pull/73) to `pyscreeze` (findings/contributions from @nulano and @radarhere) should fix this.

**Comment by asweigart** [comment]
With the fix for https://github.com/asweigart/pyscreeze/pull/73 in PyScreeze, this issue should be fixed. Just do a `pip install -U pyscreeze` to install the latest version of PyScreeze (1.0.28 has the fix). Thank you so much for pointing out this issue and the fix.

**Comment by jwhendy** [comment]
@asweigart Thank *you* for pyautogui! This was actually found in my first time using it, and it was awesome! It was also a good learning experience for me and [mostly] fun game of playing detective :)

**Comment by makorth12** [comment]
@asweigart Just had the error come up on 0.1.28 which should include the pyscreeze fix.

**Comment by JayRizzo** [comment]
Hi all,  I hope everyone is doing well.   

FYI It also is worth mentioning, I got a simliar error when reviewing #688.

In it I mention that there might be an issue with the `Image` package, at least for me on my mac,  it was complaining, as it didn't exist for some reason on my machine. (not sure if it is my fault or not.)

But, Running `pip3 install Image` fixed the issue.

I am not sure if it is related in any way, just adding for reference. 

Have a Great Day All!
