### ISSUE TITLE
String-matching within an image [Feature Request]

### ISSUE THREAD

**Issue by antchal** [asweigart/pyautogui#584]
Every now and then I come across a situation in which I change theme of a software, and then if I run PyAutoGUI's template matching program on it's screenshot, it breaks because of obvious changes in the haystack image.

Although I can solve it by doing some image processing, but what about an out of the box string-matching feature of PyAutoGUI which detects the location (or bounding box) where a particular text of interest is located within an image, irrespective of it's GUI? Something like what keras-ocr & easy-ocr provide.

This could potential ease out text-detection situations where we are currently bound to use `locateOnScreen`, `locateAllOnScreen`, or `locate` functions. For instance, documentation uses
![](https://pyautogui.readthedocs.io/en/latest/_images/calculator.png) 
as haystack and
![](https://pyautogui.readthedocs.io/en/latest/_images/calc7key.png) 
as needle image, this new functionality will require "7" instead of the "needle-image" argument.

**Comment by asweigart** [comment]
OCR is a feature I'd like to eventually add, but I need to look into it more. For now, you can check out a blog post I wrote about pytesseract and recognizing text in images and screenshots: https://inventwithpython.com/blog/2021/01/11/text-recognition-in-python-with-pytesseract/

**Comment by wanghaisheng** [comment]
@asweigart 
```
import easyocr
reader = easyocr.Reader(['ch_sim','en']) # this needs to run only once to load the model into memory
result = reader.readtext('chinese.jpg')
```
https://github.com/JaidedAI/EasyOCR
