### ISSUE TITLE
macOS - `locateOnScreen()` coordinates are off by a factor of 2

### ISSUE THREAD

**Issue by rez1-inf** [asweigart/pyautogui#589]
`locateOnScreen()` works perfectly on Ubuntu Linux but on MacOS it always adds a varying offset.
As X increases, the coordinates returned by `locateOnScreen()` increases by a certain ratio, similar for Y but increases slightly less.

Doesn't matter how many desktop/workspaces I have active, the result is the same.

**Comment by ClementDelannoySlateDigital** [comment]
On my screens, there is a factor 2 on x and y returned by locateCenterOnScreen

**Comment by rez1-inf** [comment]
> On my screens, there is a factor 2 on x and y returned by locateCenterOnScreen

that's correct. the coordinates are off by a factor of 2. so a workaround is to use `locateCenterOnScreen()` and divide the coordinates by 2 before using them.

**Comment by ClementDelannoySlateDigital** [comment]
I will reopen that because it still needs a fix even if a workaround is available

**Comment by hangj** [comment]
The factor 2 is devicePixelRatio.  
`pixelRatio = pyautogui.screenshot().size[0]/pyautogui.size().width`

**Comment by rez1-inf** [comment]
@hangj thanks... instead of a fixed factor 2, a pixel ratio would be better..

**Comment by chrischma** [comment]
very interesting!

**Comment by caiooaragao** [comment]
> The factor 2 is devicePixelRatio. `pixelRatio = pyautogui.screenshot().size[0]/pyautogui.size().width`

can u explain more about it?

**Comment by HeisenBug1** [comment]
> > The factor 2 is devicePixelRatio. `pixelRatio = pyautogui.screenshot().size[0]/pyautogui.size().width`
> 
> 
> 
> can u explain more about it?

Sometimes the screen is scaled up/down, either by default, or you can do it manually to make things bigger/smaller. This causes the LocateCenterOnScreen() or any other similar functions to be off by the factor the screen was scaled to. In my case it was a factor of 2. So instead if we use this formula to get a device pixel ratio, it'll work for every scaled screen sizes..
