### ISSUE TITLE
pyautogui.typewrite optional additional delay for newlines

### ISSUE THREAD

**Issue by richardforth** [asweigart/pyautogui#591]
At the moment we have an optional argument for delay which is to say the delay between keystrokes:

pyautogui.typewrite(myText, 0.02)

However what I am proposing is to add an optional delay when a newline is encountered, so that some programs don't wig out (eg Microsoft Teams or linux terminals).

So for example:

pyautogui.typewrite(myText, 0.02, 0.5)

would give a 0.02 second delay between kepyresses, and a half second delay after every  carriage return/newline/enter.

I am not sure how this would work under the bonnet, but I have considered a workaround whereby I split 'myText' up based on the newline character, and then typewrite each paragraph and put a sleep in between them.

For example (using semi-pseudo-code):
```python
myText = "Mary had a little lamb,
It's fleece was white as snow"

lines = myText.splitlines()

after the split, becomes:

lines = ["Mary had a little lamb,", "It's fleece was white as snow"]

for line in lines:
    pyautogui.typewrite(line, 0.02)
    pyautogui.typewrite("\n")
    time.sleep(0.5)

```

However it would be very cool if this could be implemented directly in pyautogui as a secondary optional delay.

EDIT: Added the delay back in to pseudocode, see next comment.

**Comment by richardforth** [comment]
Interestingly that code forces the program to buffer the output and paste each line in one go, so you lest the typing effect

**Comment by richardforth** [comment]
If youre interested this is what I am building:
https://github.com/richardforth/keyboardpal

**Comment by asweigart** [comment]
This is interesting, but I'm not sure there's wide enough demand for it to make it a standard part of PyAutoGUI. You could write code like this:

```
import pyautogui as pyag
import time
text = 'Hello\nGoodbye'
for line in text.split('\n'):
    pyag.typewrite(line)
    time.sleep(0.2)
```
