### ISSUE TITLE
CTRL C crashing my code.  KeyboardInterrupt

### ISSUE THREAD

**Issue by therealrobster** [asweigart/pyautogui#594]
Hi there,

When my code does a CTRL C it crashes.  This is with both:

    pyautogui.hotkey('ctrl', 'c')

and

    pyautogui.keyDown('ctrl')
    pyautogui.press('c')
    pyautogui.keyUp('ctrl')

I have the following code example:

	import pyautogui

	# failsafe in case of robot madness
	pyautogui.PAUSE = .2
	pyautogui.FAILSAFE = True

	# copy selection
	# pyautogui.hotkey('ctrl', 'c')
	pyautogui.keyDown('ctrl')
	pyautogui.press('c')
	pyautogui.keyUp('ctrl')

	# Move mouse to X 
	pyautogui.moveTo(1400, 360, .1)

	# click
	pyautogui.click()

	# select all 
	pyautogui.hotkey('ctrl', 'a')

	# paste
	pyautogui.hotkey('ctrl', 'v')

	# enter
	pyautogui.hotkey('enter')

	# Move mouse to locatoin
	pyautogui.moveTo(660, 470, .5)

	# middle click this thing to open new tab
	pyautogui.click(button='middle')

	# Move mouse to right window again
	pyautogui.moveTo(2500, 500, .1)

and here is a trackback with the line `pyautogui.hotkey('ctrl', 'c')` in action:

  Traceback (most recent call last):
    File "madmimi-email-to-search.py", line 8, in <module>
      pyautogui.hotkey('ctrl', 'c')
    File "/home/username/.local/lib/python3.8/site-packages/pyautogui/__init__.py", line 587, in wrapper
      _handlePause(kwargs.get("_pause", True))
    File "/home/username/.local/lib/python3.8/site-packages/pyautogui/__init__.py", line 631, in _handlePause
      time.sleep(PAUSE)
  KeyboardInterrupt

and here is a traceback with the other 3 lines doing the CTRL C in action and the `pyautogui.hotkey('ctrl', 'c')` commented out:

  Traceback (most recent call last):
    File "madmimi-email-to-search.py", line 10, in <module>
      pyautogui.press('c')
    File "/home/username/.local/lib/python3.8/site-packages/pyautogui/__init__.py", line 587, in wrapper
      _handlePause(kwargs.get("_pause", True))
    File "/home/username/.local/lib/python3.8/site-packages/pyautogui/__init__.py", line 631, in _handlePause
      time.sleep(PAUSE)
  KeyboardInterrupt

I note in the second example, the CTRL key is locked down after the script has crashed and I need to tap the keyboard again to turn it off.

This code worked on my old machine, but after a full re-format and re-install of everything it's now broken.

Pop!_OS 20.04 LTS
X11
Gnome 3.36.8

Thank you

**Comment by asweigart** [comment]
This is odd. What's happening is that the Ctrl-C must be being sent to the terminal window that's running the python script, and pressing Ctrl-C in a python program causes the KeyboardInterrupt exception that you're seeing. I'm not sure why it ever worked before.

Are you trying to copy the text in the terminal window running the script? Either way, this is the expected behavior, so I'm going to close this issue.
