### ISSUE TITLE
Re-publish the docs

### ISSUE THREAD

**Issue by nmstoker** [asweigart/pyautogui#602]
Thank you for this great repo.

I happened to notice that someone kindly fixed an out of date mention in the repo docs of Python 3.8 not being supported by Pillow (which is definitely no longer the case as it supports 3.9 already with an issue open for 3.10) thanks to the PR  here:

https://github.com/asweigart/pyautogui/pull/541

However it seems that despite the repo docs being fine now, the published docs are still not reflecting the change. I don't know for sure how you've got them set up but I'm guessing it simply needed someone to push a re-publishing of the docs for it to pull the latest text from the repo and everything will then be consistent.

What's currently published:
https://pyautogui.readthedocs.io/en/latest/install.html

What's in the repo:
https://github.com/asweigart/pyautogui/blob/master/docs/install.rst

**Comment by nmstoker** [comment]
Doing this would resolve the (fixed) source of confusion behind #357 too

The long outdated reference to Ubuntu problems with Pillow is also resolved in the repo docs, just not in the actually published ones, eg here:
https://pyautogui.readthedocs.io/en/latest/screenshot.html#special-notes-about-ubuntu

**Comment by nmstoker** [comment]
Hi @asweigart - am guessing you're busy. Is there a way others can push the docs update to ReadTheDocs for the above points?

**Comment by asweigart** [comment]
I've pushed the latest version of the docs on readthedocs.org just now. However, the documentation is sorely lacking and in need of updates. I'm not sure when I'll have time to go through them, but at least the latest version is built now. Thanks!
