### ISSUE TITLE
Tweening mouse x/y independently?

### ISSUE THREAD

**Issue by crotron** [asweigart/pyautogui#608]
Is it possible to tween the x- and y-components of the mouse position separately i.e. having one tweening function for the-x component and one tweening function for the y-component? If not, I think this could be a useful addition. Otherwise, your cursor is restricted to the straight line between the start and end positions.

**Comment by asweigart** [comment]
PyAutoGUI doesn't have this feature available. I suppose you could call the pytweening functions yourself and then move the mouse with your own code. This is kind of a esoteric request, so I can't justify including it as a built-in feature of PyAutoGUI. Thank you though.

I am curious though, why do you want this feature?
