### ISSUE TITLE
Can't delete this repo from the repository section of my homepage

### ISSUE THREAD

**Issue by henrymdeutsch** [asweigart/pyautogui#609]
I don't know how to remove the asweigart / pyautogui repo from the left hand corner of my homepage, under Repositories. It's not a forked repo so there's no settings option to delete it. I recently answered someone's question on the issues section of this repo so that must be what got it there.

**Comment by asweigart** [comment]
This is an issue with your GitHub account, and not PyAutoGUI. I'm closing this issue.
