### ISSUE TITLE
locateOnAllScreen not working on loop

### ISSUE THREAD

**Issue by Supercoolz1** [asweigart/pyautogui#61]
I have a website where there are multiple checkboxes or a multiple very small images but when I run the loop it only runs till 11 and then stops. Please find the code and result below 

Loop : 
for tick in pyautogui.locateAllOnScreen('ticket.png'):
    print tick

Result : C:\Users\ZEI\Desktop\study\zii automation>python click.py
(272, 251, 11, 11)
(272, 313, 11, 11)
(272, 375, 11, 11)
(272, 431, 11, 11)
(272, 513, 11, 11)
(272, 580, 11, 11)
(272, 647, 11, 11)
(272, 714, 11, 11)
(272, 770, 11, 11)
(272, 826, 11, 11)

There are around 70 check boxes and it only shows this much.
![mcheckbox](https://cloud.githubusercontent.com/assets/15200115/10705101/10e05870-79f9-11e5-8724-cab4682dd6a2.png)

**Comment by Supercoolz1** [comment]
I have got the problem cordinates were of full page nut it was not picking them correctly. any suggestion on how I can get the cordinates picked up

**Comment by asweigart** [comment]
I can reproduce this. When I try to locate all of the checkboxes in your image, it matches the top one, misses the next one down, matches the one after that, but misses the next one down, etc. There are 16 pairs of checkboxes, but PyAutoGUI is only finding 8.

**Comment by asweigart** [comment]
Could you take a screenshot and upload it? And also upload the tick.png file you are using and run the click.py code one more time, and copy/paste the output here? This way I can reproduce what is happening.

**Comment by zlorb** [comment]
Screenshots are incorrectly cropped on high-DPI displays. Windows returns display geometry data scaled for the DPI, while the actual screenshots are unscaled. Workaround: Right-click on python.exe, Properties, Compatibility tab, check 'Disable display scaling on high DPI settings'. Repeat for pythonw.exe.

Thanks to: https://github.com/ludios/Desktopmagic

**Comment by asweigart** [comment]
Thanks! There seem to be a few bugs revolving around high density displays on Windows and Mac. I'll start looking into them.

**Comment by asweigart** [comment]
I've added the DPI scaling fix to 0.9.35, so hopefully this is now fixed.
