### ISSUE TITLE
Weak and obsolete Rubicon dependency for Python 3.9

### ISSUE THREAD

**Issue by macdeport** [asweigart/pyautogui#616]
For several months, I have been encountering this Python warning:

```
/Users/alain/Library/Python/3.9/lib/python/site-packages/rubicon/objc/ctypes_patch.py:21: UserWarning: rubicon.objc.ctypes_patch has only been tested with Python 3.4 through 3.8. You are using Python 3.9.6. Most likely things will work properly, but you may experience crashes if Python's internals have changed significantly.
  warnings.warn(

```
My temporary (and weak) workaround :

```Python
import warnings
warnings.filterwarnings('ignore',
                     message='rubicon.objc.ctypes_patch has only been tested ')
import pyautogui
...

```

**Comment by asweigart** [comment]
What version of PyAutoGUI are you using? We used to use rubicon, but then switched back to pyobjc. Is this in the latest PyAutoGUI?

**Comment by macdeport** [comment]
Python 3.9.7 / PyAutoGUI 0.9.53

**Comment by macdeport** [comment]
Perhaps useful to update this:
![floating-screenshot-140623](https://user-images.githubusercontent.com/26068595/133254964-461498d3-e6de-413e-a8d6-03d6ab090b43.jpg)

**Comment by asweigart** [comment]
Ah, sorry about this. The documentation wasn't updated to match the rollback on rubicon to pyobjc. macOS needs the pyobjc-core and pyobjc module installed (in that order).

I'll update the docs.

**Comment by macdeport** [comment]
@asweigart https://github.com/asweigart/pyautogui/issues/616#issuecomment-91885396
![floating-screenshot-204723](https://user-images.githubusercontent.com/26068595/134726082-4b6b4e8d-38c5-4664-b3e3-7cf99495498f.jpg)
![floating-screenshot-204847](https://user-images.githubusercontent.com/26068595/134726213-b66fb130-0e91-43ab-8a9c-b9b3648c3c29.jpg)
