### ISSUE TITLE
importing pyautogui breaks tkinter Checkbutton

### ISSUE THREAD

**Issue by GabeMillikan** [asweigart/pyautogui#635]
Code:
```py
import tkinter as tk
from tkinter import ttk
import pyautogui

w = tk.Tk()
ttk.Checkbutton(w, text = "Checkbox").grid()
w.mainloop()
```
Result:
![KwUqCTWl58](https://user-images.githubusercontent.com/44247924/139580777-4ecb8826-f131-4fab-afd9-141c0de80527.gif)

New code after removing pyautogui import:
```py
import tkinter as tk
from tkinter import ttk
#import pyautogui

w = tk.Tk()
ttk.Checkbutton(w, text = "Checkbox").grid()
w.mainloop()
```
Result:
![apXWoyEXIc](https://user-images.githubusercontent.com/44247924/139580798-1847e410-c2de-48ef-b57d-f918d195ad09.gif)

I am on 64bit Windows 11 and using Python 3.8.10, but I'm not sure that this is platform specific. Would love for people on other systems to check if the same issue occurs.

**Comment by GabeMillikan** [comment]
P.S. If I use `.pack()` instead of `.grid()`, then the checkbox starts out small, whereas with `.gird()` you have to hover over it for it to become small.

**Comment by GabeMillikan** [comment]
I actually located the problem. pyautogui imports pyscreeze, which executes this code:
```py
import ctypes
ctypes.windll.user32.SetProcessDPIAware()
```
Which is the cause of this bug.
I now believe that this is actually a Tkinter bug, and not pyscreeze nor pyautogui's problem (since the ctypes code is required for them to take accurate screenshots).

**Comment by macdeport** [comment]
The size of window seems the cause of this "bug": superposition of checkbox area and resize handle...
This code works perfectly (Mac OS X / Python 3.9.6):
```Python
import tkinter as tk
from tkinter import ttk
import pyautogui

w = tk.Tk()
f = tk.Frame()
w.title('Better')
w.geometry('150x40') # sufficient window size
ttk.Checkbutton(f, text = "Checkbox").pack()
f.grid()
w.mainloop()

```
