### ISSUE TITLE
tripleClick causes crash on MacOS

### ISSUE THREAD

**Issue by Jarno-de-Wit** [asweigart/pyautogui#698]
The tripleClick function, when called on MacOS, will cause the program to crash with a `TypeError: not enough arguments for format string`.
This issue arises in line [1168](https://github.com/asweigart/pyautogui/blob/667161b072e89b4a25b806c5f2ca616e6c0aeec3/pyautogui/__init__.py#L1168) when formatting the string "%s,3,%s%s" % (x, y). This string expects 3 values to format (namely (button, x, y)), but the "button" variable is missing from the formatting section.

To fix, update the line to:
`        _logScreenshot(logScreenshot, "click", "%s,3,%s,%s" % (button, x, y), folder=".")`

**Comment by JayRizzo** [comment]
Verified. 

```python
import pyautogui

pyautogui.tripleClick(150, 150)
pyautogui.tripleClick(logScreenshot=True, x=150, y=150)

```

Both worked as expected with this change on my MBP.

Thanks @Jarno-de-Wit !
