### ISSUE TITLE
Use case with Docker

### ISSUE THREAD

**Issue by davins90** [asweigart/pyautogui#725]
Hi all,

I would like to build a docker container containing a python code able to use pyautogui modules to do some stuff on the host PC of the docker. 

Is it possible?

I would like to use docker to let other of my colleagues use this code on other machines (Mac, Linux, Windows)

Thanks very much,

Daniele

**Comment by asweigart** [comment]
I'm not sure, I don't have experience with Docker. In general, PyAutoGUI hasn't worked on headless setups.
