### ISSUE TITLE
Doesn't work with Cyrilic.

### ISSUE THREAD

**Issue by sheriv** [asweigart/pyautogui#79]
`pyautogui.typewrite('раз два три')` creates a couple of spaces but doesn't write any Cyrillic letters.

**Comment by Timmate** [comment]
pyautogui works only with ASCII characters.

**Comment by asweigart** [comment]
Folding this into issue https://github.com/asweigart/pyautogui/issues/137

**Comment by Pydwel** [comment]
@sheriv , Нашёл хитрость как сделать так,чтобы pyautogui писал на русском ! К примеру : Создаём txt файл и вписываем туда русские слова находясь на английской раскладке.Т.е к примеру "Ничоси" будет выглядеть так :
Ybxjcb
Потом в скрипте прописываем функцию которая берёт эти слова из txt по строчке и делает с ней pyautogui.typewrite().
Открываем терминал.Вписываем python3 скрипт.py и **перед тем** как нажать Enter чтобы скрипт начал свою работу - мы меняем раскладку на русскую и вуаля ! Pyautogui пишет слова так,как мы и хотели !

**Comment by kot-mapku3** [comment]
> @sheriv , Нашёл хитрость как сделать так,чтобы pyautogui писал на русском ! К примеру : Создаём txt файл и вписываем туда русские слова находясь на английской раскладке.Т.е к примеру "Ничоси" будет выглядеть так :
> Ybxjcb
> Потом в скрипте прописываем функцию которая берёт эти слова из txt по строчке и делает с ней pyautogui.typewrite().
> Открываем терминал.Вписываем python3 скрипт.py и **перед тем** как нажать Enter чтобы скрипт начал свою работу - мы меняем раскладку на русскую и вуаля ! Pyautogui пишет слова так,как мы и хотели !

Слишком неудобно, но это хоть что-то! Спасибо!

**Comment by Alex1396** [comment]
https://github.com/asweigart/pyautogui/issues/137#issuecomment-465523499 - Заскриптованный вариант того решения, который предложили выше.
