### ISSUE TITLE
Does not work for non-American keyboard keys.

### ISSUE THREAD

**Issue by asweigart** [asweigart/pyautogui#8]
I'll have to look into how other keyboards produce characters such as é or あ. PyAutoGUI currently uses virtual key codes (the "VK" stuff in the source) to do this, but this needs to be expanded to other characters.

**Comment by hugoesb** [comment]
I made scripts using VK write é, ã, ê, etc (in portuguese we use a lot letter like this). I simulated click a sequence, for instance, for é I simulate click 0xdb and after click  0x45. So, when you put teclar('é') (my script function equivalent to typewrite in PyAutoGUI) the functions in fact press 0xdb and after 0x45.

I mapped this kind of letter like this:
         'á':[0xDB, 0x41], 'é':[0xDB, 0x45], 'í':[0xDB, 0x49], 'ó':[0xDB, 0x4F], 'ú':[0xDB, 0x55],
         'à':['0xDB', 0x41], 'è':['0xDB', 0x45], 'ì':['0xDB', 0x49], 'ò':['0xDB', 0x4F], 'ù':['0xDB', 0x55],
         'ã':[0xDE, 0x41], 'õ':[0xDE, 0x4F], 'â':['0xDE', 0x41], 'ê':['0xDE', 0x45], 'ô':['0xDE', 0x4F], 
         'Á':[0xDB, '0x41'], 'É':[0xDB, '0x45'], 'Í':[0xDB, '0x49'], 'Ó':[0xDB, '0x4F'], 'Ú':[0xDB, '0x55'],
         'À':['0xDB', '0x41'], 'È':['0xDB', '0x45'], 'Ì':['0xDB', '0x49'], 'Ò':['0xDB', '0x4F'], 'Ù':['0xDB', '0x55'],
         'Ã':[0xDE, '0x41'], 'Õ':[0xDE, '0x4F'], 'Â':['0xDE', '0x41'], 'Ê':['0xDE', '0x45'], 'Ô':['0xDE', '0x4F'],

This works for keyboard ABNT2 (the most common in Brazil).

I used like reference the followed page:
 https://msdn.microsoft.com/en-us/library/windows/desktop/dd375731(v=vs.85).aspx

I'm sorry, but I could't realize how I can implement this in PyAutoGUI code. Maybe some argument defining keyboard in __init__ like:

KEYBOARD = ''

And if you define pyautogui.KEYBOARD = 'ABNT2' it should update the keyboardMapping dictiionary.

**Comment by asweigart** [comment]
Folding this into issue #137
