### ISSUE TITLE
Add German support for typewrite()

### ISSUE THREAD

**Issue by asweigart** [asweigart/pyautogui#82]
From a user's email:

I use PyAutoGUI-0.9.33-py3.4.egg-info in one of my programs. When I use the function pyautogui.typewrite special characters like ö,ä,ü,#,@ ß, do not work.

I found an workaround for me on the following side:

http://stackoverflow.com/questions/13289777/how-can-i-send-keyboard-commands-hold-release-simultanous-with-a-python-script

Maybe you can use this code for windows, so special characters are also supported if it not already work now.

Thank you for your time and thanks for PyAutoGUI :)

Following the code that works for me:

import ctypes
import time

SendInput = ctypes.windll.user32.SendInput

PUL = ctypes.POINTER(ctypes.c_ulong)
class KeyBdInput(ctypes.Structure):
    _fields_ = [("wVk", ctypes.c_ushort),
                ("wScan", ctypes.c_ushort),
                ("dwFlags", ctypes.c_ulong),
                ("time", ctypes.c_ulong),
                ("dwExtraInfo", PUL)]

class HardwareInput(ctypes.Structure):
    _fields_ = [("uMsg", ctypes.c_ulong),
                ("wParamL", ctypes.c_short),
                ("wParamH", ctypes.c_ushort)]

class MouseInput(ctypes.Structure):
    _fields_ = [("dx", ctypes.c_long),
                ("dy", ctypes.c_long),
                ("mouseData", ctypes.c_ulong),
                ("dwFlags", ctypes.c_ulong),
                ("time",ctypes.c_ulong),
                ("dwExtraInfo", PUL)]

class Input_I(ctypes.Union):
    _fields_ = [("ki", KeyBdInput),
                 ("mi", MouseInput),
                 ("hi", HardwareInput)]

class Input(ctypes.Structure):
    _fields_ = [("type", ctypes.c_ulong),
                ("ii", Input_I)]

def writetext(text_unicode):
        def PressKey_local(KeyUnicode):
            extra = ctypes.c_ulong(0)
            ii_ = Input_I()
            ii_.ki = KeyBdInput( 0, KeyUnicode, KEYEVENTF_UNICODE, 0, ctypes.pointer(extra) )
            x = Input( ctypes.c_ulong(1), ii_ )
            ctypes.windll.user32.SendInput(1, ctypes.pointer(x), ctypes.sizeof(x))
        def ReleaseKey_local(KeyUnicode):
            extra = ctypes.c_ulong(0)
            ii_ = Input_I()
            ii_.ki = KeyBdInput( 0, KeyUnicode, KEYEVENTF_UNICODE|KEYEVENTF_KEYUP, 0, ctypes.pointer(extra) )
            x = Input( ctypes.c_ulong(1), ii_ )
            ctypes.windll.user32.SendInput(1, ctypes.pointer(x), ctypes.sizeof(x))  
        for c in text_unicode:
            PressKey_local(ord(c))
            ReleaseKey_local(ord(c))

writetext("Ölgemälde")

**Comment by Timmate** [comment]
When I run this code, I get `NameError: 'KEYEVENTF_UNICODE' is not defined.`
When I specify these values like this:
```
KEYEVENTF_UNICODE = 0x0004
KEYEVENTF_KEYUP = 0x0002
```
I get the following error:

```
Traceback (most recent call last):
  File "C:\Users\Tim\Desktop\type_cyrillic.py", line 60, in <module>
    writetext('Я олень')
  File "C:\Users\Tim\Desktop\type_cyrillic.py", line 42, in writetext
    PressKey_local(ord(c))
  File "C:\Users\Tim\Desktop\type_cyrillic.py", line 48, in PressKey_local
    ii_.ki = KeyBdInput( 0, KeyUnicode, KEYEVENTF_UNICODE, 0, ctypes.pointer(extra) )
TypeError: too many initializers

```
Do you have any ideas?

**Comment by asweigart** [comment]
Folding this into issue https://github.com/asweigart/pyautogui/issues/137
