### ISSUE TITLE
Add function to drag & drop file

### ISSUE THREAD

**Issue by thenewguy** [asweigart/pyautogui#825]
It would be helpful if there was a drag & drop file option. It would be helpful if the file could be provided as a file path on disk and then given coordinates of where to drop on screen.

**Comment by mikigo** [comment]
Maybe you can give it a try

```python
pyautogui.locateOnScreen()
pyautogui.dragTo()
```

**Comment by thenewguy** [comment]
In my mind I was thinking of a drag and drop by image path. 

I think that yours would work if the file explorer was open - but would not work for what I am doing as the application is the only image displayed on the headless screen.

I was hoping to simulate what you've described. I'll close this issue as too specific. I've solved my problem with a different solution
