### ISSUE TITLE
pyautogui not working in chrome dino

### ISSUE THREAD

**Issue by AasheeshLikePanner** [asweigart/pyautogui#828]
Pyautogui not working when using in Chrome dino. When I am using 
```
pyautogui.press('down') / pyautogui.press('num2') 
```
This keys uses for to make dino crouch. This keys are not working with chrome. But all keys like up and others are working fine with chrome dino.

**Comment by AasheeshLikePanner** [comment]
Also ```  pyautogui.press('down') ```  working in other environments like ide or writing  cursor down

**Comment by henygebremedhin** [comment]
[like]  Heny Gebremedhin reacted to your message:
________________________________
