### ISSUE TITLE
Pyautogui.screenshot(region=) does not accept a variable from another file

### ISSUE THREAD

**Issue by Sqidy-P** [asweigart/pyautogui#837]
Here is the code:
```
import main
import pyautogui


# main() contains game_cords = GetWindowRect(FindWindow(None, "..."))
cords = main.game_cords

def get_cards():

    # Debug
    print(main.game_cords)

    game = pyautogui.screenshot(region=cords)
    game.save(r"C:\\Users\\Sqidy\\PycharmProjects\\Solitare\\UI\\Game\\screenshot.png")


    pass
```
Once ran, this is the error:
```
...\venv\lib\site-packages\pyscreeze\__init__.py", line 540, in _screenshot_win32
    assert len(region) == 4, 'region argument must be a tuple of four ints'
AssertionError: region argument must be a tuple of four ints
```

I am on a windows system, latest version of python, using Pycharm. It will take a variable, but when I try to take it from another file, in this case being my main.py, it will not accept it as it's tuple.

**Comment by Sqidy-P** [comment]
While I do think this should be fixed, it has nothing to do with pyautogui, it's just how python is coded for some reason.

**Comment by Sqidy-P** [comment]
While I do think this should be fixed, it has nothing to do with pyautogui, it's just how python is coded for some reason.

**Comment by encleadus** [comment]
I am receiving the same error, is there any solution on this?
