### ISSUE TITLE
docs: why not recommend conda instead of pip pyobc?

### ISSUE THREAD

**Issue by varnell-holdings** [asweigart/pyautogui#86]
Twice gave up using pyautogui on mac because could not get pip pyobjc to compile
conda install -c jcarlin pyobjc-framework-quartz=3.0.4
worked like a charm in a couple of seconds
love pyautogui!!!!

**Comment by digwanderlust** [comment]
pyobjc has some problems installing on El Capitan, I was able to get it to install by doing:

MACOSX_DEPLOYMENT_TARGET=10.11 pip install pyobjc

your milage may vary.

**Comment by asweigart** [comment]
Could you write up detailed steps for doing this and make a documentation PR?

**Comment by asweigart** [comment]
Closing this, as I think the issue with pyobjc is fixed now.
