### ISSUE TITLE
Would you like to write function "assertAndClick()" ?

### ISSUE THREAD

**Issue by qiujieqiong** [asweigart/pyautogui#89]
assertAndClick(image, timeout=30, clicks=1, interval=1.0, button='left', duration=0.0, tween=linear, pause=None, _pause=True)  equals below steps:

buttonx, buttony = pyautogui.locateCenterOnScreen('button.png') # returns (x, y) of matching region 
pyautogui.click(buttonx, buttony) # clicks the center of where the button was found 

assertAndClick() means to replace the coordinates with the image, if screen found the image in 30 seconds, then click the center of images, otherwise return false

**Comment by asweigart** [comment]
This can be folded into this issue: https://github.com/asweigart/pyautogui/issues/129

Thanks for the suggestion!
